# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo/zm-qa

    environment:
      # Customize the JVM maximum heap limit
      #MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      #- restore_cache:
          #keys:
          #- v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          #- v1-dependencies-

      #- run: mvn dependency:go-offline

      #- save_cache:
          #paths:
          #  - ~/.m2
          #key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      #- run: mvn integration-test
      - run : git clone https://github.com/Zimbra/zm-zcs.git /home/circleci/repo/zm-zcs
      - run : git clone https://github.com/Zimbra/zimbra-package-stub.git /home/circleci/repo/zimbra-package-stub
      - run : cd /home/circleci/repo
      - run : mkdir .zcs-deps
      - run : cd /home/circleci/repo/.zcs-deps && wget https://files.zimbra.com/repository/ant-contrib/ant-contrib-1.0b1.jar
      - run : cd /home/circleci/repo/zm-qa 
      - run : ant jar
