# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
# a
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo/zm-soap-harness

    environment:
      # Customize the JVM maximum heap limit
      #MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
        
      # run tests!
      #- run: mvn integration-test
      - run : git clone https://github.com/Zimbra/zm-zcs.git /home/circleci/repo/zm-zcs
      - run : git clone https://github.com/Zimbra/zimbra-package-stub.git /home/circleci/repo/zimbra-package-stub
      - run : mkdir /home/circleci/.zcs-deps
      - run : mkdir -p /home/circleci/.ivy/cache/
      - run : cd /home/circleci/.zcs-deps && wget https://files.zimbra.com/repository/ant-contrib/ant-contrib-1.0b1.jar
      - run : git clone https://github.com/Zimbra/zm-mailbox.git /home/circleci/repo/zm-mailbox
      - run : cd /home/circleci/repo/zm-mailbox && ant publish-local-all -Dzimbra.buildinfo.version=8.8.0_GA
      - run : cd /home/circleci/repo/zm-soap-harness
      - run : ant clean, zm-network-soap-content, staf-jar, build-soap-data-file
