Return-Path: david_tycast@example.com
Received: from mail.domain.kucera.tes (LHLO mail.domain.kucera.tes)
 (192.1.2.215) by mail.domain.kucera.tes with LMTP; Mon, 25 Aug 2008
 08:11:38 -0400 (EDT)
Received: from web62504.mail.re1.yahoo.tes (unknown [192.1.2.1])
	by mail.domain.kucera.tes (Postfix) with SMTP id 3474B14A0001
	for <d.debiase@example.com>; Mon, 25 Aug 2008 08:11:22 -0400 (EDT)
X-Spam-DCC: CollegeOfNewCaledonia: ipcgateway.domain.kucera.tes 1189; Body=1
	Fuz1=1 Fuz2=1
X-Spam-Checker-Version: SpamAssassin 3.2.3 (2007-08-08) on
	ipcgateway.domain.kucera.tes
X-Spam-Level: *********************
X-Spam-Status: No, score=21.6 required=22.0 tests=BAYES_99,HTML_MESSAGE,IXHASH,
	LOGINHASH,LOGINHASH2,MIME_QP_LONG_LINE,RDNS_NONE,SARE_MLB_Stock6 autolearn=no
	version=3.2.3
X-Spam-Report: 
	*  9.0 BAYES_99 BODY: Bayesian spam probability is 99 to 100%
	*      [score: 1.0000]
	*  1.6 SARE_MLB_Stock6 BODY: ML obfuscated ticker symbols
	*  4.5 LOGINHASH BODY: iXhash says its spam
	*  2.5 IXHASH BODY: iXhash says its spam
	*  0.0 HTML_MESSAGE BODY: HTML included in message
	*  2.5 LOGINHASH2 BODY: iXhash says its spam
	*  1.4 MIME_QP_LONG_LINE RAW: Quoted-printable line longer than 76 chars
	*  0.1 RDNS_NONE Delivered to trusted network by a host with no rDNS
X-Envelope-From: david_tycast@example.com miketybo@example.com miketybo@example.com jabroni064@example.com nobgr@example.com ellencakes@example.com michaelggrankin@example.com ikhardy44@example.com taraberry@example.com flowerbug98@example.com catherinedicker@example.com ccrein@example.com syoung@example.com michaelggrankin@example.com ikhardy44@example.com catherinedicker@example.com syoung@example.com michaelggrankin@example.com ikhardy44@example.com catherinedicker@example.com nobgr@example.com nobgr@example.com ellencakes@example.com ellencakes@example.com michaelggrankin@example.com michaelggrankin@example.com ikhardy44@example.com ikhardy44@example.com taraberry@example.com taraberry@example.com flowerbug98@example.com flowerbug98@example.com catherinedicker@example.com catherinedicker@example.com ccrein@example.com ccrein@example.com
Received: from yahoo.tes miketybo ([69.147.75.96]) by ipcgateway (Copfilter 0.84beta3a)
X-Filtered-With-Copfilter: Version 0.84beta3a (ProxSMTP 1.6)
X-Copfilter-Virus-Scanned: ClamAV 0.91.2/8084 - Mon Aug 25 04:02:23 2008
Received: (qmail 64533 invoked by uid 60001); 25 Aug 2008 12:11:21 -0000
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws;
  s=s1024; d=yahoo.tes;
  h=X-YMail-OSG:Received:X-Mailer:Date:From:Reply-To:Subject:To:MIME-Version:Content-Type:Message-ID;
  b=fqFcS7TQAJWfwBLH2OUiLICQl+0ROpbSn+P10Kb7ioWUVVry4C0RoCGtmwpTVi1r7pMTsWwCx4tiLMF9GSsAwp+Se9aBqgLr93NgPDI1lb+MuRzVYmuP7ayuS8V2rHlJovQQVcKuYHQSipiTkz/OLCVw3cPssJkcxITVWQYmX0k=;
X-YMail-OSG: 8Dge76MVM1nqX9vnaxLP80ULUPvRY3giGFMo0i7ohMqtUR9A0ZtjScYmDIH_aPhawKtrw.3DigdVoKDjiURxCdbW4A.6oNQCw2TeHn0g2WscHPyNjnAj3ZSvt5nrgw.GvDTDc_q.72uS9IpGUL3aPM2a
Received: from [76.205.99.147] by web62504.mail.re1.yahoo.tes via HTTP; Mon, 25 Aug 2008 05:11:21 PDT
X-Mailer: YahooMailWebService/0.7.218.2
Date: Mon, 25 Aug 2008 05:11:21 -0700 (PDT)
From: DAVID TYCAST <david_tycast@example.com>
Reply-To: david_tycast@example.com
Subject: Fwd: NATURAL HIGHS
To: Big Al <advocon@example.com>, Andrew Boothe <BOOTHEAC@example.com>,
  Brian Hetzer <brianhetzer@example.com>, Mike Debrouse <cccmd316@example.com>,
  Dan Debiase <d.debiase@example.com>,
  Barb Mazanec <datamom1@example.com>, Ed Fabis <ed@example.com>,
  John Lees <jlees@example.com>, Mike Tycast <miketybo@example.com>,
  Pat Clampitt <paclampi@example.com>, shookfamily4@example.com,
  Candy McCausland <texaspeach1@example.com>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="0-831998417-1219666281=:64492"
Message-ID: <814145.64492.qm@example.com>
X-Copfilter-Originating-IP: 69.147.75.96

--0-831998417-1219666281=:64492
Content-Type: multipart/alternative; boundary="0-1701094651-1219666281=:64492"

--0-1701094651-1219666281=:64492
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable



--- On Sun, 8/24/08, miketybo@example.com <miketybo@example.com> wrote:

From: miketybo@example.com <miketybo@example.com>
Subject: Fwd: NATURAL HIGHS ( HAVE QUESTIONS ON #29)
To: tycast24@example.com, jabroni064@example.com, CINDERX1@example.com, C=
INDERX1@example.com, pdt_sat@example.com, datamom1@example.com, MCSUNMOON@example.com=
AL.tes, MTYCAST001@example.com, MSAVARD001@example.com, david_tycast@example.com=
o.tes, casper3243@example.com
Date: Sunday, August 24, 2008, 3:47 PM


j


-----Original Message-----
From: peter cipro <jabroni064@example.com>
To: blackbetty@example.com
Sent: Sun, 24 Aug 2008 3:23 pm
Subject: Fwd: FW: NATURAL HIGHS ( HAVE QUESTIONS ON #29)




Note: forwarded message attached.=20


Attached Message



From:
William Burns <WBURNS@example.com>

To:
Pat Burns <ellencakes@example.com>

Cc:
Michael Tycast <MTYCAST@example.com>; Nicholas Cipro <NCIPRO@example.com>; Pete=
r Taraska <PTARASKA@example.com>; safetyjayne@example.com; peter cipro <jabro=
ni064@example.com>; daryl salyers <docsalyers@example.com>

Subject:
Fwd: FW: NATURAL HIGHS ( HAVE QUESTIONS ON #29)

Date:
Sun, 24 Aug 2008 07:32:04 -0400


William A. Burns
Power Department Heavy Equipment
Phone:  216-575-3806
Fax:  216-575-3814
wburns@example.com
www.riderta.tes

>>> Pat Burns <ellencakes@example.com> 8/23/2008 5:35 PM >>>



From: nobgr@example.com: ellencakes@example.com: Fw: FW:
NATURAL HIGHSDate: Thu, 21 Aug 2008 21:51:40 -0400



=20
----- Original Message -----=20
From: Pam Rasgaitis=20
To: Sue Conroy ; Susan Dudas ; Ricky Gareau ; Linda Hanacek ; Meredith
Liedtke ; Linda Malise ; Jerry Noble ; Tim Rasgaitis ; Cathy Robinson ;
Lydia Rock ; Lisa Sandoval ; Suzy Sanker ; Carol Schultz ; Jean Yousefi

Sent: Thursday, August 21, 2008 6:01 PM
Subject: Fwd: FW: NATURAL HIGHS
Note: forwarded message attached. --Forwarded Message Attachment--From:
CatchaLTR@example.com: Wed, 20 Aug 2008 13:26:48 -0400Subject: Fwd: FW:
NATURAL HIGHSTo: beaglelover320@example.com; Pooh121549@example.com;
pamras@example.com; ddukovac@example.com; vsoanes@example.com;
jenabear520@example.com; stacyyoung1971@example.com=20
=20


It's only a deal if it's where you want to go. Find your travel deal
here.--Forwarded Message Attachment--Date: Wed, 20 Aug 2008 10:37:40
-0400From: stacyyoung1971@example.com: angela.alderson1@example.com;
bjbandish@example.com; cwbbqcateringco@example.com;
cyndysota34287@example.com; catchaLTR@example.com;
most_definitly@example.com; debra.gallipo@example.com;
lincliff@example.com; dpriff3@example.com; fleiniebop1@example.com;
happyholly@example.com; KHightower@example.com;
lloseemail@example.com; ybbyancey@example.com; preycroft@example.com;
tammy@example.com; youngmyakka@example.com: Fwd: FW: NATURAL HIGHS

---------- Forwarded message ----------From: Stacy Young
<SYoung@example.com>Date: Wed, Aug 20, 2008 at 10:35 AMSubject: FW:
NATURAL HIGHSTo: stacyyoung1971@example.com: Lisa Robertson
<LRobertson@example.com>


=20
=20

Stacy Young
Underwriter
FWCJUA
Tel:  941.378.7400 ext 5427
Fax:  941.487.2532
syoung@example.com=20
=20
***************************************************************************=
**************This
message may contain information that is privileged, confidential and
exempt fromdisclosure under applicable law. If you are not the intended
recipient (or authorized toact on behalf of the intended recipient) of
this message, you may not disclose, forward,distribute, copy, or use
this message or its contents.  If you have received thiscommunication in
error, please notify us immediately by return e-mail and delete
theoriginal message from your e-mail
system.********************************************************************=
*********************
=20


From: Lisa Robertson Sent: Wednesday, August 20, 2008 7:54 AMTo: Janis
Scott; Lisa M. Pisani; Stacy Young; Susan J. Schmidtke; Terri
WoodsSubject: FW: NATURAL HIGHS
=20
=20
=20

=20
Lisa Robertson
Underwriting Supervisor
FWCJUA
Phone: 941-378-7400
Fax: 941-487-2531
lrobertson@example.com=20
=20


From: michael rankin [mailto:michaelggrankin@example.com] Sent: Monday,
August 18, 2008 7:51 PMTo: Lisa RobertsonSubject: FW: NATURAL HIGHS
=20




From: ikhardy44@example.com: taraberry@example.com; flowerbug98@example.com;
dennis.smith86@example.com; karlbeulah@example.com; lbaker45@example.com;
michaelggrankin@example.com; nikki67888@example.com; rolin3991@example.com;
suziewhi@example.com: FW: NATURAL HIGHSDate: Mon, 18 Aug 2008
19:35:40 -0400

irene..............
=20



From: catherinedicker@example.com: CCREIN@example.com;
MaryBeth@example.com; amcgourty@example.com;
SMSCMAC@example.com; ikhardy44@example.com; Moeful@example.com;
HUNNA002@example.com; bgb4477@example.com: Fwd: NATURAL HIGHSDate:
Sun, 17 Aug 2008 18:31:03 +0000

=20

=20


Date: Fri, 8 Aug 2008 13:37:50 +0000=20







=20









=20


----- Original Message -----=20

Subject: Fwd: NATURAL HIGHS

=20




=20






















Natural Highs=20



















Please make sure you forward this back to me . . You'll see why at the
end. Think about them one at a time before going on to the next one. It
Does Make You Feel Good, especially the thought at the end of #44.=20

1. Falling in love.=20

2. Laughing so hard your face hurts.=20

3. A hot shower.=20

4. No lines at the supermarket .=20

5. A special glance.=20

6. Getting mail.=20

7. Taking a drive on a pretty road.=20

8. Hearing your favorite song on the radio.=20

9. Lying in bed listening to the rain outside.=20

10. Hot towels fresh out of the dryer.=20

11. Chocolate milkshake (vanilla or strawberry).=20

12. A bubble bath.=20

13. Giggling.=20

15. The beach.=20

16. Finding a 20 dollar bill in your coat from last winter.=20

17. Laughing at yourself.=20

18. Looking into their eyes and knowing they Love you=20

19. Midnight phone calls that last for hours.=20

20. Running through sprinklers.=20

21. Laughing for absolutely no reason at all.=20

22. Having someone tell you that you're beautiful.=20

23. Laughing at an inside joke with FRIENDS=20

24. Accidentally overhearing someone say something nice about you.=20

25. Waking up and realizing you still have a few hours left to sleep.=20

26. Your first kiss (either the very first or with a new partner).=20

27. Making new friends or spending time with old ones.=20

28. Playing with a new puppy.=20

29. Having someone play with your hair.=20

30. Sweet dreams.=20

31. Hot chocolate.=20

32. Road trips with friends.=20

33. Swinging on swings.=20

34. Making eye contact with a cute stranger.=20

35. Making chocolate chip cookies.=20

36. Having your friends send you homemade cookies.=20

37. Holding hands with someone you care about.=20

38. Running into an old friend and realizing that some things (good or
bad) never change.=20

39. Watching the expression on someone's face as they open a much
desired present from you.=20

40. Watching the sunrise.=20

41. Getting out of bed every morning and being grateful for another
beautiful day.=20

42. Knowing that somebody misses you.=20

43. Getting a hug from someone you care about deeply.=20

44. Knowing you've done the right thing, no matter what other people
think.=20

Pass on These Natural Highs to at Least 7 People in the Next Half Hour
and Something Fantastic Will Happen to You in the Next Few Hours.=20

Be sure to send it back to the person who sent it to you!=20
Lord, keep Your arm around my shoulder and Your hand over my mouth .=20


=20

=20

=20


=20


=20

=20






=20
=20
____________________________________________________________ Click for
free info on college degrees.




It's time to go back to school! Get the latest trends and gadgets that
make the grade on AOL Shopping.=20
=20




It's time to go back to school! Get the latest trends and gadgets that
make the grade on AOL Shopping.=20
=20



See what people are saying about Windows Live. Check out featured
posts. Check It Out!=20



Talk to your Yahoo! Friends via Windows Live Messenger. Find Out How
_________________________________________________________________
See what people are saying about Windows Live.  Check out featured
posts.
http://www.windowslive.tes/connect?ocid=3DTXT_TAGLM_WL_connect2_082008=20
---------------------------------------------------------------------


Scanning of this message and addition of this footer is performed
by SurfControl E-mail Filter software in conjunction with=20
virus detection software.



Attached Message



From:
Stacy Young <stacyyoung1971@example.com>

To:
Marlana <catchaLTR@example.com>; Mom <cwbbqcateringco@example.com>; Pat <preycroft@=
chriscraft.tes>; Veronica <youngmyakka@example.com>; Sharon & Dan <dpriff3@example.com=
link.tes>; Dad & Linda <lincliff@example.com>; Kelley Hightower <KHightower=
@example.com>; Nicole <ybbyancey@example.com>; Tammy <tammy@example.com=
et>; Charlie <most_definitly@example.com>; Cousin Angie <angela.alderson1@=
us.army.mil>; Barbara <bjbandish@example.com>; Debra <debra.gallipo@example.com=
.tes>; Cyndy <cyndysota34287@example.com>; Tena <fleiniebop1@example.com>; Laur=
ie <lloseemail@example.com>; Holly <happyholly@example.com>

Subject:
Fwd: FW: NATURAL HIGHS

Date:
Wed, 20 Aug 2008 10:37:40 -0400




---------- Forwarded message ----------
From: Stacy Young <SYoung@example.com>
Date: Wed, Aug 20, 2008 at 10:35 AM
Subject: FW: NATURAL HIGHS
To: stacyyoung1971@example.com
Cc: Lisa Robertson <LRobertson@example.com>





=A0
=A0

Stacy Young
Underwriter
FWCJUA
Tel:=A0 941.378.7400 ext 5427
Fax:=A0 941.487.2532
syoung@example.com
=A0
***************************************************************************=
**************
This message may contain information that is privileged, confidential and e=
xempt from
disclosure under applicable law. If you are not the intended recipient (or =
authorized to
act on behalf of the intended recipient) of this message, you may not discl=
ose, forward,
distribute, copy, or use this message or its contents.=A0 If you have recei=
ved this
communication in error, please notify us immediately by return e-mail and d=
elete the
original message from your e-mail system.
***************************************************************************=
**************
=A0


From: Lisa Robertson=20
Sent: Wednesday, August 20, 2008 7:54 AM
To: Janis Scott; Lisa M. Pisani; Stacy Young; Susan J. Schmidtke; Terri Woo=
ds
Subject: FW: NATURAL HIGHS
=A0
=A0
=A0

=A0
Lisa Robertson
Underwriting Supervisor
FWCJUA
Phone: 941-378-7400
Fax: 941-487-2531
lrobertson@example.com
=A0


From: michael rankin [mailto:michaelggrankin@example.com]=20
Sent: Monday, August 18, 2008 7:51 PM
To: Lisa Robertson
Subject: FW: NATURAL HIGHS
=A0






From: ikhardy44@example.com
To: taraberry@example.com; flowerbug98@example.com; dennis.smith86@example.com; karlbeu=
lah@example.com; lbaker45@example.com; michaelggrankin@example.com; nikki67888@=
aol.tes; rolin3991@example.com; suziewhi@example.com
Subject: FW: NATURAL HIGHS
Date: Mon, 18 Aug 2008 19:35:40 -0400



irene..............
=A0



From: catherinedicker@example.com
To: CCREIN@example.com; MaryBeth@example.com; amcgourty@example.com=
et; SMSCMAC@example.com; ikhardy44@example.com; Moeful@example.com; HUNNA002@example.com=
m; bgb4477@example.com
Subject: Fwd: NATURAL HIGHS
Date: Sun, 17 Aug 2008 18:31:03 +0000

=A0

=A0


Date: Fri, 8 Aug 2008 13:37:50 +0000=20







=A0









=A0


----- Original Message -----=20

Subject: Fwd: NATURAL HIGHS

=A0




=A0






















Natural Highs=20



















Please make sure you forward this back to me . . You'll see why at the end.=
 Think about them one at a time before going on to the next one. It Does Ma=
ke You Feel Good, especially the thought at the end of #44.=20

1. Falling in love.=20

2. Laughing so hard your face hurts.=20

3. A hot shower.=20

4. No lines at the supermarket .=20

5. A special glance.=20

6. Getting mail.=20

7. Taking a drive on a pretty road.=20

8. Hearing your favorite song on the radio.=20

9. Lying in bed listening to the rain outside.=20

10. Hot towels fresh out of the dryer.=20

11. Chocolate milkshake (vanilla or strawberry).=20

12. A bubble bath.=20

13. Giggling.=20

15. The beach.=20

16. Finding a 20 dollar bill in your coat from last winter.=20

17. Laughing at yourself.=20

18. Looking into their eyes and knowing they Love you=20

19. Midnight phone calls that last for hours.=20

20. Running through sprinklers.=20

21. Laughing for absolutely no reason at all.=20

22. Having someone tell you that you're beautiful.=20

23. Laughing at an inside joke with FRIENDS=20

24. Accidentally overhearing someone say something nice about you.=20

25. Waking up and realizing you still have a few hours left to sleep.=20

26. Your first kiss (either the very first or with a new partner).=20

27. Making new friends or spending time with old ones.=20

28. Playing with a new puppy.=20

29. Having someone play with your hair.=20

30. Sweet dreams.=20

31. Hot chocolate.=20

32. Road trips with friends.=20

33. Swinging on swings.=20

34. Making eye contact with a cute stranger.=20

35. Making chocolate chip cookies.=20

36. Having your friends send you homemade cookies.=20

37. Holding hands with someone you care about.=20

38. Running into an old friend and realizing that some things (good or bad)=
 never change.=20

39. Watching the expression on someone's face as they open a much desired p=
resent from you.=20

40. Watching the sunrise.=20

41. Getting out of bed every morning and being grateful for another beautif=
ul day.=20

42. Knowing that somebody misses you.=20

43. Getting a hug from someone you care about deeply.=20

44. Knowing you've done the right thing, no matter what other people think.=
=20

Pass on These Natural Highs to at Least 7 People in the Next Half Hour and =
Something Fantastic Will Happen to You in the Next Few Hours.=20

Be sure to send it back to the person who sent it to you!=20
Lord, keep Your arm around my shoulder and Your hand over my mouth .=20


=A0

=A0

=A0


=A0


=A0

=A0






=A0
=A0


____________________________________________________________=20
Click for free info on college degrees.




It's time to go back to school! Get the latest trends and gadgets that make=
 the grade on AOL Shopping.=20
=A0




It's time to go back to school! Get the latest trends and gadgets that make=
 the grade on AOL Shopping.=20
=A0



See what people are saying about Windows Live. Check out featured posts. Ch=
eck It Out!=20



Talk to your Yahoo! Friends via Windows Live Messenger. Find Out How





Attached Message



From:
CatchaLTR@example.com

To:
Pooh121549@example.com; pamras@example.com; beaglelover320@example.com; stacyyoung1=
971@example.com; jenabear520@example.com; ddukovac@example.com; vsoanes@example.com=
om

Subject:
Fwd: FW: NATURAL HIGHS

Date:
Wed, 20 Aug 2008 13:26:48 -0400

=A0





It's only a deal if it's where you want to go. Find your travel deal here.


Attached Message



From:
Stacy Young <stacyyoung1971@example.com>

To:
Marlana <catchaLTR@example.com>; Mom <cwbbqcateringco@example.com>; Pat <preycroft@=
chriscraft.tes>; Veronica <youngmyakka@example.com>; Sharon & Dan <dpriff3@example.com=
link.tes>; Dad & Linda <lincliff@example.com>; Kelley Hightower <KHightower=
@example.com>; Nicole <ybbyancey@example.com>; Tammy <tammy@example.com=
et>; Charlie <most_definitly@example.com>; Cousin Angie <angela.alderson1@=
us.army.mil>; Barbara <bjbandish@example.com>; Debra <debra.gallipo@example.com=
.tes>; Cyndy <cyndysota34287@example.com>; Tena <fleiniebop1@example.com>; Laur=
ie <lloseemail@example.com>; Holly <happyholly@example.com>

Subject:
Fwd: FW: NATURAL HIGHS

Date:
Wed, 20 Aug 2008 10:37:40 -0400




---------- Forwarded message ----------
From: Stacy Young <SYoung@example.com>
Date: Wed, Aug 20, 2008 at 10:35 AM
Subject: FW: NATURAL HIGHS
To: stacyyoung1971@example.com
Cc: Lisa Robertson <LRobertson@example.com>





=A0
=A0

Stacy Young
Underwriter
FWCJUA
Tel:=A0 941.378.7400 ext 5427
Fax:=A0 941.487.2532
syoung@example.com
=A0
***************************************************************************=
**************
This message may contain information that is privileged, confidential and e=
xempt from
disclosure under applicable law. If you are not the intended recipient (or =
authorized to
act on behalf of the intended recipient) of this message, you may not discl=
ose, forward,
distribute, copy, or use this message or its contents.=A0 If you have recei=
ved this
communication in error, please notify us immediately by return e-mail and d=
elete the
original message from your e-mail system.
***************************************************************************=
**************
=A0


From: Lisa Robertson=20
Sent: Wednesday, August 20, 2008 7:54 AM
To: Janis Scott; Lisa M. Pisani; Stacy Young; Susan J. Schmidtke; Terri Woo=
ds
Subject: FW: NATURAL HIGHS
=A0
=A0
=A0

=A0
Lisa Robertson
Underwriting Supervisor
FWCJUA
Phone: 941-378-7400
Fax: 941-487-2531
lrobertson@example.com
=A0


From: michael rankin [mailto:michaelggrankin@example.com]=20
Sent: Monday, August 18, 2008 7:51 PM
To: Lisa Robertson
Subject: FW: NATURAL HIGHS
=A0






From: ikhardy44@example.com
To: taraberry@example.com; flowerbug98@example.com; dennis.smith86@example.com; karlbeu=
lah@example.com; lbaker45@example.com; michaelggrankin@example.com; nikki67888@=
aol.tes; rolin3991@example.com; suziewhi@example.com
Subject: FW: NATURAL HIGHS
Date: Mon, 18 Aug 2008 19:35:40 -0400



irene..............
=A0



From: catherinedicker@example.com
To: CCREIN@example.com; MaryBeth@example.com; amcgourty@example.com=
et; SMSCMAC@example.com; ikhardy44@example.com; Moeful@example.com; HUNNA002@example.com=
m; bgb4477@example.com
Subject: Fwd: NATURAL HIGHS
Date: Sun, 17 Aug 2008 18:31:03 +0000

=A0

=A0


Date: Fri, 8 Aug 2008 13:37:50 +0000=20







=A0









=A0


----- Original Message -----=20

Subject: Fwd: NATURAL HIGHS

=A0




=A0






















Natural Highs=20



















Please make sure you forward this back to me . . You'll see why at the end.=
 Think about them one at a time before going on to the next one. It Does Ma=
ke You Feel Good, especially the thought at the end of #44.=20

1. Falling in love.=20

2. Laughing so hard your face hurts.=20

3. A hot shower.=20

4. No lines at the supermarket .=20

5. A special glance.=20

6. Getting mail.=20

7. Taking a drive on a pretty road.=20

8. Hearing your favorite song on the radio.=20

9. Lying in bed listening to the rain outside.=20

10. Hot towels fresh out of the dryer.=20

11. Chocolate milkshake (vanilla or strawberry).=20

12. A bubble bath.=20

13. Giggling.=20

15. The beach.=20

16. Finding a 20 dollar bill in your coat from last winter.=20

17. Laughing at yourself.=20

18. Looking into their eyes and knowing they Love you=20

19. Midnight phone calls that last for hours.=20

20. Running through sprinklers.=20

21. Laughing for absolutely no reason at all.=20

22. Having someone tell you that you're beautiful.=20

23. Laughing at an inside joke with FRIENDS=20

24. Accidentally overhearing someone say something nice about you.=20

25. Waking up and realizing you still have a few hours left to sleep.=20

26. Your first kiss (either the very first or with a new partner).=20

27. Making new friends or spending time with old ones.=20

28. Playing with a new puppy.=20

29. Having someone play with your hair.=20

30. Sweet dreams.=20

31. Hot chocolate.=20

32. Road trips with friends.=20

33. Swinging on swings.=20

34. Making eye contact with a cute stranger.=20

35. Making chocolate chip cookies.=20

36. Having your friends send you homemade cookies.=20

37. Holding hands with someone you care about.=20

38. Running into an old friend and realizing that some things (good or bad)=
 never change.=20

39. Watching the expression on someone's face as they open a much desired p=
resent from you.=20

40. Watching the sunrise.=20

41. Getting out of bed every morning and being grateful for another beautif=
ul day.=20

42. Knowing that somebody misses you.=20

43. Getting a hug from someone you care about deeply.=20

44. Knowing you've done the right thing, no matter what other people think.=
=20

Pass on These Natural Highs to at Least 7 People in the Next Half Hour and =
Something Fantastic Will Happen to You in the Next Few Hours.=20

Be sure to send it back to the person who sent it to you!=20
Lord, keep Your arm around my shoulder and Your hand over my mouth .=20


=A0

=A0

=A0


=A0


=A0

=A0






=A0
=A0


____________________________________________________________=20
Click for free info on college degrees.




It's time to go back to school! Get the latest trends and gadgets that make=
 the grade on AOL Shopping.=20
=A0




It's time to go back to school! Get the latest trends and gadgets that make=
 the grade on AOL Shopping.=20
=A0



See what people are saying about Windows Live. Check out featured posts. Ch=
eck It Out!=20



Talk to your Yahoo! Friends via Windows Live Messenger. Find Out How




[Image Removed]=20



Get the MapQuest Toolbar. Directions, Traffic, Gas Prices & More! =0A=0A=0A=
      
--0-1701094651-1219666281=:64492
Content-Type: multipart/related; boundary="0-505355714-1219666281=:64492"

--0-505355714-1219666281=:64492
Content-Type: text/html; charset=us-ascii

<table cellspacing="0" cellpadding="0" border="0" ><tr><td valign="top" style="font: inherit;"><BR><BR>--- On <B>Sun, 8/24/08, miketybo@example.com <I>&lt;miketybo@example.com&gt;</I></B> wrote:<BR>
<BLOCKQUOTE style="PADDING-LEFT: 5px; MARGIN-LEFT: 5px; BORDER-LEFT: rgb(16,16,255) 2px solid">From: miketybo@example.com &lt;miketybo@example.com&gt;<BR>Subject: Fwd: NATURAL HIGHS ( HAVE QUESTIONS ON #29)<BR>To: tycast24@example.com, jabroni064@example.com, CINDERX1@example.com, CINDERX1@example.com, pdt_sat@example.com, datamom1@example.com, MCSUNMOON@example.com, MTYCAST001@example.com, MSAVARD001@example.com, david_tycast@example.com, casper3243@example.com<BR>Date: Sunday, August 24, 2008, 3:47 PM<BR><BR>
<DIV id=yiv693535679>j<BR><BR><BR>-----Original Message-----<BR>From: peter cipro &lt;jabroni064@example.com&gt;<BR>To: blackbetty@example.com<BR>Sent: Sun, 24 Aug 2008 3:23 pm<BR>Subject: Fwd: FW: NATURAL HIGHS ( HAVE QUESTIONS ON #29)<BR><BR>
<DIV id=AOLMsgPart_3_509f09b8-680e-42dc-b2a0-66b9d4955120><BR><BR>Note: forwarded message attached. </DIV>
<DIV id=AOLMsgPart_4_509f09b8-680e-42dc-b2a0-66b9d4955120 style="MARGIN: 10px">
<DIV style="BORDER-RIGHT: #7da8d4 1px solid; BORDER-TOP: #7da8d4 1px solid; BACKGROUND: #f9f9f9; FONT: 11px arial; BORDER-LEFT: #7da8d4 1px solid; BORDER-BOTTOM: #7da8d4 1px solid">
<DIV style="PADDING-RIGHT: 3px; PADDING-LEFT: 3px; BACKGROUND: #b5ddfa; PADDING-BOTTOM: 3px; FONT: 11px arial; PADDING-TOP: 3px">Attached Message</DIV>
<TABLE>
<TBODY>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px" noWrap>From:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">William Burns &lt;WBURNS@example.com&gt;</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">To:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Pat Burns &lt;ellencakes@example.com&gt;</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Cc:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Michael Tycast &lt;MTYCAST@example.com&gt;; Nicholas Cipro &lt;NCIPRO@example.com&gt;; Peter Taraska &lt;PTARASKA@example.com&gt;; safetyjayne@example.com; peter cipro &lt;jabroni064@example.com&gt;; daryl salyers &lt;docsalyers@example.com&gt;</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Subject:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Fwd: FW: NATURAL HIGHS ( HAVE QUESTIONS ON #29)</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Date:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Sun, 24 Aug 2008 07:32:04 -0400</TD></TR></TBODY></TABLE></DIV>
<DIV id=AOLMsgPart_6_509f09b8-680e-42dc-b2a0-66b9d4955120 style="FONT-SIZE: 12px; MARGIN: 0px; COLOR: #000; FONT-FAMILY: Tahoma, Verdana, Arial, Sans-Serif; BACKGROUND-COLOR: #fff"><PRE style="FONT-SIZE: 9pt"><TT>

William A. Burns
Power Department Heavy Equipment
Phone:  216-575-3806
Fax:  216-575-3814
<A href="mailto:wburns@example.com" target=_blank rel=nofollow>wburns@example.com</A>
<A href="http://www.riderta.tes/" target=_blank rel=nofollow>www.riderta.tes</A>

&gt;&gt;&gt; Pat Burns &lt;<A href="mailto:ellencakes@example.com" target=_blank rel=nofollow>ellencakes@example.com</A>&gt; 8/23/2008 5:35 PM &gt;&gt;&gt;



From: <A href="mailto:nobgr@example.com" target=_blank rel=nofollow>nobgr@example.com</A>: <A href="mailto:ellencakes@example.com" target=_blank rel=nofollow>ellencakes@example.com</A>: Fw: FW:
NATURAL HIGHSDate: Thu, 21 Aug 2008 21:51:40 -0400



 
----- Original Message ----- 
From: Pam Rasgaitis 
To: Sue Conroy ; Susan Dudas ; Ricky Gareau ; Linda Hanacek ; Meredith
Liedtke ; Linda Malise ; Jerry Noble ; Tim Rasgaitis ; Cathy Robinson ;
Lydia Rock ; Lisa Sandoval ; Suzy Sanker ; Carol Schultz ; Jean Yousefi

Sent: Thursday, August 21, 2008 6:01 PM
Subject: Fwd: FW: NATURAL HIGHS
Note: forwarded message attached. --Forwarded Message Attachment--From:
<A href="mailto:CatchaLTR@example.com" target=_blank rel=nofollow>CatchaLTR@example.com</A>: Wed, 20 Aug 2008 13:26:48 -0400Subject: Fwd: FW:
NATURAL HIGHSTo: <A href="mailto:beaglelover320@example.com" target=_blank rel=nofollow>beaglelover320@example.com</A>; <A href="mailto:Pooh121549@example.com" target=_blank rel=nofollow>Pooh121549@example.com</A>;
<A href="mailto:pamras@example.com" target=_blank rel=nofollow>pamras@example.com</A>; <A href="mailto:ddukovac@example.com" target=_blank rel=nofollow>ddukovac@example.com</A>; <A href="mailto:vsoanes@example.com" target=_blank rel=nofollow>vsoanes@example.com</A>;
<A href="mailto:jenabear520@example.com" target=_blank rel=nofollow>jenabear520@example.com</A>; <A href="mailto:stacyyoung1971@example.com" target=_blank rel=nofollow>stacyyoung1971@example.com</A> 
 


It's only a deal if it's where you want to go. Find your travel deal
here.--Forwarded Message Attachment--Date: Wed, 20 Aug 2008 10:37:40
-0400From: <A href="mailto:stacyyoung1971@example.com" target=_blank rel=nofollow>stacyyoung1971@example.com</A>: <A href="mailto:angela.alderson1@example.com" target=_blank rel=nofollow>angela.alderson1@example.com</A>;
<A href="mailto:bjbandish@example.com" target=_blank rel=nofollow>bjbandish@example.com</A>; <A href="mailto:cwbbqcateringco@example.com" target=_blank rel=nofollow>cwbbqcateringco@example.com</A>;
<A href="mailto:cyndysota34287@example.com" target=_blank rel=nofollow>cyndysota34287@example.com</A>; <A href="mailto:catchaLTR@example.com" target=_blank rel=nofollow>catchaLTR@example.com</A>;
<A href="mailto:most_definitly@example.com" target=_blank rel=nofollow>most_definitly@example.com</A>; <A href="mailto:debra.gallipo@example.com" target=_blank rel=nofollow>debra.gallipo@example.com</A>;
<A href="mailto:lincliff@example.com" target=_blank rel=nofollow>lincliff@example.com</A>; <A href="mailto:dpriff3@example.com" target=_blank rel=nofollow>dpriff3@example.com</A>; <A href="mailto:fleiniebop1@example.com" target=_blank rel=nofollow>fleiniebop1@example.com</A>;
<A href="mailto:happyholly@example.com" target=_blank rel=nofollow>happyholly@example.com</A>; <A href="mailto:KHightower@example.com" target=_blank rel=nofollow>KHightower@example.com</A>;
<A href="mailto:lloseemail@example.com" target=_blank rel=nofollow>lloseemail@example.com</A>; <A href="mailto:ybbyancey@example.com" target=_blank rel=nofollow>ybbyancey@example.com</A>; <A href="mailto:preycroft@example.com" target=_blank rel=nofollow>preycroft@example.com</A>;
<A href="mailto:tammy@example.com" target=_blank rel=nofollow>tammy@example.com</A>; <A href="mailto:youngmyakka@example.com" target=_blank rel=nofollow>youngmyakka@example.com</A>: Fwd: FW: NATURAL HIGHS

---------- Forwarded message ----------From: Stacy Young
&lt;<A href="mailto:SYoung@example.com" target=_blank rel=nofollow>SYoung@example.com</A>&gt;Date: Wed, Aug 20, 2008 at 10:35 AMSubject: FW:
NATURAL HIGHSTo: <A href="mailto:stacyyoung1971@example.com" target=_blank rel=nofollow>stacyyoung1971@example.com</A>: Lisa Robertson
&lt;<A href="mailto:LRobertson@example.com" target=_blank rel=nofollow>LRobertson@example.com</A>&gt;


 
 

Stacy Young
Underwriter
FWCJUA
Tel:  941.378.7400 ext 5427
Fax:  941.487.2532
<A href="mailto:syoung@example.com" target=_blank rel=nofollow>syoung@example.com</A> 
 
*****************************************************************************************This
message may contain information that is privileged, confidential and
exempt fromdisclosure under applicable law. If you are not the intended
recipient (or authorized toact on behalf of the intended recipient) of
this message, you may not disclose, forward,distribute, copy, or use
this message or its contents.  If you have received thiscommunication in
error, please notify us immediately by return e-mail and delete
theoriginal message from your e-mail
system.*****************************************************************************************
 


From: Lisa Robertson Sent: Wednesday, August 20, 2008 7:54 AMTo: Janis
Scott; Lisa M. Pisani; Stacy Young; Susan J. Schmidtke; Terri
WoodsSubject: FW: NATURAL HIGHS
 
 
 

 
Lisa Robertson
Underwriting Supervisor
FWCJUA
Phone: 941-378-7400
Fax: 941-487-2531
<A href="mailto:lrobertson@example.com" target=_blank rel=nofollow>lrobertson@example.com</A> 
 


From: michael rankin [<A href="mailto:michaelggrankin@example.com?" target=_blank rel=nofollow>mailto:michaelggrankin@example.com</A>] Sent: Monday,
August 18, 2008 7:51 PMTo: Lisa RobertsonSubject: FW: NATURAL HIGHS
 




From: <A href="mailto:ikhardy44@example.com" target=_blank rel=nofollow>ikhardy44@example.com</A>: <A href="mailto:taraberry@example.com" target=_blank rel=nofollow>taraberry@example.com</A>; <A href="mailto:flowerbug98@example.com" target=_blank rel=nofollow>flowerbug98@example.com</A>;
<A href="mailto:dennis.smith86@example.com" target=_blank rel=nofollow>dennis.smith86@example.com</A>; <A href="mailto:karlbeulah@example.com" target=_blank rel=nofollow>karlbeulah@example.com</A>; <A href="mailto:lbaker45@example.com" target=_blank rel=nofollow>lbaker45@example.com</A>;
<A href="mailto:michaelggrankin@example.com" target=_blank rel=nofollow>michaelggrankin@example.com</A>; <A href="mailto:nikki67888@example.com" target=_blank rel=nofollow>nikki67888@example.com</A>; <A href="mailto:rolin3991@example.com" target=_blank rel=nofollow>rolin3991@example.com</A>;
<A href="mailto:suziewhi@example.com" target=_blank rel=nofollow>suziewhi@example.com</A>: FW: NATURAL HIGHSDate: Mon, 18 Aug 2008
19:35:40 -0400

irene..............
 



From: <A href="mailto:catherinedicker@example.com" target=_blank rel=nofollow>catherinedicker@example.com</A>: <A href="mailto:CCREIN@example.com" target=_blank rel=nofollow>CCREIN@example.com</A>;
<A href="mailto:MaryBeth@example.com" target=_blank rel=nofollow>MaryBeth@example.com</A>; <A href="mailto:amcgourty@example.com" target=_blank rel=nofollow>amcgourty@example.com</A>;
<A href="mailto:SMSCMAC@example.com" target=_blank rel=nofollow>SMSCMAC@example.com</A>; <A href="mailto:ikhardy44@example.com" target=_blank rel=nofollow>ikhardy44@example.com</A>; <A href="mailto:Moeful@example.com" target=_blank rel=nofollow>Moeful@example.com</A>;
<A href="mailto:HUNNA002@example.com" target=_blank rel=nofollow>HUNNA002@example.com</A>; <A href="mailto:bgb4477@example.com" target=_blank rel=nofollow>bgb4477@example.com</A>: Fwd: NATURAL HIGHSDate:
Sun, 17 Aug 2008 18:31:03 +0000

 

 


Date: Fri, 8 Aug 2008 13:37:50 +0000 







 









 


----- Original Message ----- 

Subject: Fwd: NATURAL HIGHS

 




 






















Natural Highs 



















Please make sure you forward this back to me . . You'll see why at the
end. Think about them one at a time before going on to the next one. It
Does Make You Feel Good, especially the thought at the end of #44. 

1. Falling in love. 

2. Laughing so hard your face hurts. 

3. A hot shower. 

4. No lines at the supermarket . 

5. A special glance. 

6. Getting mail. 

7. Taking a drive on a pretty road. 

8. Hearing your favorite song on the radio. 

9. Lying in bed listening to the rain outside. 

10. Hot towels fresh out of the dryer. 

11. Chocolate milkshake (vanilla or strawberry). 

12. A bubble bath. 

13. Giggling. 

15. The beach. 

16. Finding a 20 dollar bill in your coat from last winter. 

17. Laughing at yourself. 

18. Looking into their eyes and knowing they Love you 

19. Midnight phone calls that last for hours. 

20. Running through sprinklers. 

21. Laughing for absolutely no reason at all. 

22. Having someone tell you that you're beautiful. 

23. Laughing at an inside joke with FRIENDS 

24. Accidentally overhearing someone say something nice about you. 

25. Waking up and realizing you still have a few hours left to sleep. 

26. Your first kiss (either the very first or with a new partner). 

27. Making new friends or spending time with old ones. 

28. Playing with a new puppy. 

29. Having someone play with your hair. 

30. Sweet dreams. 

31. Hot chocolate. 

32. Road trips with friends. 

33. Swinging on swings. 

34. Making eye contact with a cute stranger. 

35. Making chocolate chip cookies. 

36. Having your friends send you homemade cookies. 

37. Holding hands with someone you care about. 

38. Running into an old friend and realizing that some things (good or
bad) never change. 

39. Watching the expression on someone's face as they open a much
desired present from you. 

40. Watching the sunrise. 

41. Getting out of bed every morning and being grateful for another
beautiful day. 

42. Knowing that somebody misses you. 

43. Getting a hug from someone you care about deeply. 

44. Knowing you've done the right thing, no matter what other people
think. 

Pass on These Natural Highs to at Least 7 People in the Next Half Hour
and Something Fantastic Will Happen to You in the Next Few Hours. 

Be sure to send it back to the person who sent it to you! 
Lord, keep Your arm around my shoulder and Your hand over my mouth . 


 

 

 


 


 

 






 
 
____________________________________________________________ Click for
free info on college degrees.




It's time to go back to school! Get the latest trends and gadgets that
make the grade on AOL Shopping. 
 




It's time to go back to school! Get the latest trends and gadgets that
make the grade on AOL Shopping. 
 



See what people are saying about Windows Live. Check out featured
posts. Check It Out! 



Talk to your Yahoo! Friends via Windows Live Messenger. Find Out How
_________________________________________________________________
See what people are saying about Windows Live.  Check out featured
posts.
<A href="http://www.windowslive.tes/connect?ocid=TXT_TAGLM_WL_connect2_082008" target=_blank rel=nofollow>http://www.windowslive.tes/connect?ocid=TXT_TAGLM_WL_connect2_082008</A> 
---------------------------------------------------------------------


Scanning of this message and addition of this footer is performed
by SurfControl E-mail Filter software in conjunction with 
virus detection software.
</TT></PRE></DIV>
<DIV id=AOLMsgPart_7_509f09b8-680e-42dc-b2a0-66b9d4955120 style="MARGIN: 10px">
<DIV style="BORDER-RIGHT: #7da8d4 1px solid; BORDER-TOP: #7da8d4 1px solid; BACKGROUND: #f9f9f9; FONT: 11px arial; BORDER-LEFT: #7da8d4 1px solid; BORDER-BOTTOM: #7da8d4 1px solid">
<DIV style="PADDING-RIGHT: 3px; PADDING-LEFT: 3px; BACKGROUND: #b5ddfa; PADDING-BOTTOM: 3px; FONT: 11px arial; PADDING-TOP: 3px">Attached Message</DIV>
<TABLE>
<TBODY>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px" noWrap>From:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Stacy Young &lt;stacyyoung1971@example.com&gt;</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">To:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Marlana &lt;catchaLTR@example.com&gt;; Mom &lt;cwbbqcateringco@example.com&gt;; Pat &lt;preycroft@example.com&gt;; Veronica &lt;youngmyakka@example.com&gt;; Sharon &amp; Dan &lt;dpriff3@example.com&gt;; Dad &amp; Linda &lt;lincliff@example.com&gt;; Kelley Hightower &lt;KHightower@example.com&gt;; Nicole &lt;ybbyancey@example.com&gt;; Tammy &lt;tammy@example.com&gt;; Charlie &lt;most_definitly@example.com&gt;; Cousin Angie &lt;angela.alderson1@example.com&gt;; Barbara &lt;bjbandish@example.com&gt;; Debra &lt;debra.gallipo@example.com&gt;; Cyndy &lt;cyndysota34287@example.com&gt;; Tena &lt;fleiniebop1@example.com&gt;; Laurie &lt;lloseemail@example.com&gt;; Holly &lt;happyholly@example.com&gt;</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Subject:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Fwd: FW: NATURAL HIGHS</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Date:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Wed, 20 Aug 2008 10:37:40 -0400</TD></TR></TBODY></TABLE></DIV>
<DIV id=AOLMsgPart_12_509f09b8-680e-42dc-b2a0-66b9d4955120>
<DIV dir=ltr><BR><BR>
<DIV class=gmail_quote>---------- Forwarded message ----------<BR>From: <B class=gmail_sendername>Stacy Young</B> <SPAN dir=ltr>&lt;<A href="mailto:SYoung@example.com" target=_blank rel=nofollow>SYoung@example.com</A>&gt;</SPAN><BR>Date: Wed, Aug 20, 2008 at 10:35 AM<BR>Subject: FW: NATURAL HIGHS<BR>To: <A href="mailto:stacyyoung1971@example.com" target=_blank rel=nofollow>stacyyoung1971@example.com</A><BR>Cc: Lisa Robertson &lt;<A href="mailto:LRobertson@example.com" target=_blank rel=nofollow>LRobertson@example.com</A>&gt;<BR><BR><BR>
<DIV lang=EN-US>
<DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV>
<DIV><SPAN style="FONT-SIZE: 13.5pt; COLOR: #1f497d">Stacy Young</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Underwriter</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">FWCJUA</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Tel:&nbsp; 941.378.7400 ext 5427</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Fax:&nbsp; 941.487.2532</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d"><A href="mailto:syoung@example.com" target=_blank rel=nofollow>syoung@example.com</A></SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: black">*****************************************************************************************<BR>This message may contain information that is privileged, confidential and exempt from<BR>disclosure under applicable law. If you are not the intended recipient (or authorized to<BR>act on behalf of the intended recipient) of this message, you may not disclose, forward,<BR>distribute, copy, or use this message or its contents.&nbsp; If you have received this<BR>communication in error, please notify us immediately by return e-mail and delete the<BR>original message from your e-mail system.<BR>*****************************************************************************************</SPAN><SPAN style="COLOR: black"></SPAN></DIV></DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV>
<DIV style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: #b5c4df 1pt solid; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; BORDER-LEFT: medium none; PADDING-TOP: 3pt; BORDER-BOTTOM: medium none">
<DIV><B><SPAN style="FONT-SIZE: 10pt">From:</SPAN></B><SPAN style="FONT-SIZE: 10pt"> Lisa Robertson <BR><B>Sent:</B> Wednesday, August 20, 2008 7:54 AM<BR><B>To:</B> Janis Scott; Lisa M. Pisani; Stacy Young; Susan J. Schmidtke; Terri Woods<BR><B>Subject:</B> FW: NATURAL HIGHS</SPAN></DIV></DIV></DIV>
<DIV>&nbsp;</DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV>
<DIV><SPAN style="COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Lisa Robertson</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Underwriting Supervisor</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">FWCJUA</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Phone: 941-378-7400</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Fax: 941-487-2531</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d"><A href="mailto:lrobertson@example.com" target=_blank rel=nofollow>lrobertson@example.com</A></SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV></DIV>
<DIV><SPAN style="COLOR: #1f497d">&nbsp;</SPAN><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d"></SPAN></DIV>
<DIV>
<DIV style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: #b5c4df 1pt solid; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; BORDER-LEFT: medium none; PADDING-TOP: 3pt; BORDER-BOTTOM: medium none">
<DIV><B><SPAN style="FONT-SIZE: 10pt">From:</SPAN></B><SPAN style="FONT-SIZE: 10pt"> michael rankin [mailto:<A href="mailto:michaelggrankin@example.com" target=_blank rel=nofollow>michaelggrankin@example.com</A>] <BR><B>Sent:</B> Monday, August 18, 2008 7:51 PM<BR><B>To:</B> Lisa Robertson<BR><B>Subject:</B> FW: NATURAL HIGHS</SPAN></DIV></DIV></DIV>
<DIV>&nbsp;</DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt"><BR><BR></SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt">From: <A href="mailto:ikhardy44@example.com" target=_blank rel=nofollow>ikhardy44@example.com</A><BR>To: <A href="mailto:taraberry@example.com" target=_blank rel=nofollow>taraberry@example.com</A>; <A href="mailto:flowerbug98@example.com" target=_blank rel=nofollow>flowerbug98@example.com</A>; <A href="mailto:dennis.smith86@example.com" target=_blank rel=nofollow>dennis.smith86@example.com</A>; <A href="mailto:karlbeulah@example.com" target=_blank rel=nofollow>karlbeulah@example.com</A>; <A href="mailto:lbaker45@example.com" target=_blank rel=nofollow>lbaker45@example.com</A>; <A href="mailto:michaelggrankin@example.com" target=_blank rel=nofollow>michaelggrankin@example.com</A>; <A href="mailto:nikki67888@example.com" target=_blank rel=nofollow>nikki67888@example.com</A>; <A href="mailto:rolin3991@example.com" target=_blank rel=nofollow>rolin3991@example.com</A>; <A href="mailto:suziewhi@example.com" target=_blank
 rel=nofollow>suziewhi@example.com</A><BR>Subject: FW: NATURAL HIGHS<BR>Date: Mon, 18 Aug 2008 19:35:40 -0400<BR><BR></SPAN></DIV>
<DIV>
<DIV><SPAN style="BORDER-RIGHT: windowtext 1pt solid; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt solid; PADDING-LEFT: 0in; FONT-SIZE: 10pt; PADDING-BOTTOM: 0in; BORDER-LEFT: windowtext 1pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: windowtext 1pt solid"><IMG height=12 alt="Image removed by sender." src="cid:1.1498461367@example.com" width=12 border=0></SPAN><SPAN style="FONT-SIZE: 10pt">irene..............</SPAN><SPAN style="FONT-SIZE: 10pt"></SPAN></DIV></DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt">From: <A href="mailto:catherinedicker@example.com" target=_blank rel=nofollow>catherinedicker@example.com</A><BR>To: <A href="mailto:CCREIN@example.com" target=_blank rel=nofollow>CCREIN@example.com</A>; <A href="mailto:MaryBeth@example.com" target=_blank rel=nofollow>MaryBeth@example.com</A>; <A href="mailto:amcgourty@example.com" target=_blank rel=nofollow>amcgourty@example.com</A>; <A href="mailto:SMSCMAC@example.com" target=_blank rel=nofollow>SMSCMAC@example.com</A>; <A href="mailto:ikhardy44@example.com" target=_blank rel=nofollow>ikhardy44@example.com</A>; <A href="mailto:Moeful@example.com" target=_blank rel=nofollow>Moeful@example.com</A>; <A href="mailto:HUNNA002@example.com" target=_blank rel=nofollow>HUNNA002@example.com</A>; <A href="mailto:bgb4477@example.com" target=_blank rel=nofollow>bgb4477@example.com</A><BR>Subject: Fwd: NATURAL HIGHS<BR>Date: Sun, 17 Aug 2008 18:31:03
 +0000</SPAN></DIV>
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV></DIV>
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV></DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">Date: Fri, 8 Aug 2008 13:37:50 +0000 </SPAN></DIV>
<TABLE cellSpacing=0 cellPadding=0 border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; PADDING-LEFT: 4pt; PADDING-BOTTOM: 0in; MARGIN: 5pt 0in 5pt 3.75pt; BORDER-LEFT: black 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<TABLE cellSpacing=0 cellPadding=0 border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">----- Original Message ----- </SPAN></DIV>
<DIV>
<DIV><B><SPAN style="FONT-SIZE: 10pt">Subject:</SPAN></B><SPAN style="FONT-SIZE: 10pt"> Fwd: NATURAL HIGHS</SPAN></DIV></DIV></DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV>
<DIV>
<DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>&nbsp;</DIV>
<DIV>
<TABLE cellSpacing=0 cellPadding=0 border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<DIV>
<DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: windowtext 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<TABLE style="BACKGROUND: white; MARGIN-LEFT: 10.75pt; WIDTH: 97.8%" cellSpacing=0 cellPadding=0 width="97%" border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: windowtext 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<BLOCKQUOTE style="MARGIN-TOP: 5pt; MARGIN-BOTTOM: 5pt">
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV><B><I><U><SPAN style="FONT-SIZE: 36pt; COLOR: black">N</SPAN></U></I></B><B><I><U><SPAN style="FONT-SIZE: 36pt; COLOR: #990000">atural Highs </SPAN></U></I></B></DIV></DIV></DIV></DIV></DIV></DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV style="MARGIN-BOTTOM: 5pt">
<DIV>
<DIV style="MARGIN-BOTTOM: 7.5pt; MARGIN-LEFT: 7.5pt; MARGIN-RIGHT: 7.5pt">
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #990000">Please make </SPAN></I></B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #990000">sure<B> you forward this back to me . . You'll see why at the end. Think about them one at a time before going on to the next one. It Does Make You Feel Good, especially the thought at the end of #44. </B></SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">1. Falling in love. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">2. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff8000">Laughing so hard your face hurts. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">3. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff0080">A hot shower. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">4. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0000a0">No lines at the supermarket</SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900"> . </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">5. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #808040">A special glance. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">6. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400040">Getting mail. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">7. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080ff">Taking a drive on a pretty road. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">8. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff80ff">Hearing your favorite song on the radio. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">9. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: maroon">Lying in bed listening to the rain outside. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">10. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080ff">Hot towels fresh out of the dryer. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">11. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #008040">Chocolate milkshake (vanilla or strawberry). </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">12. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8000ff">A bubble bath. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">13. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: red">Giggling. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">15. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080ff">The beach. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">16. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff0080">Finding a 20 dollar bill in your coat from last winter. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">17. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #808040">Laughing at yourself. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">18. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080c0">Looking into their eyes and knowing they Love you </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">19. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #804040">Midnight phone calls that last for hours. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">20. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400080">Running through sprinklers.</SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900"> </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">21. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff5353">Laughing for absolutely no reason at all. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">22. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #000040">Having someone tell you that you're beautiful. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">23. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400080">Laughing at an inside joke with FRIENDS </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">24. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff8000">Accidentally overhearing someone say something nice about you. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">25. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080ff">Waking up and realizing you still have a few hours left to sleep. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">26. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff80ff">Your first kiss (either the very first or with a new partner). </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">27. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080c0">Making new friends or spending time with old ones. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">28. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400000">Playing with a new puppy. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">29. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: blue">Having someone play with your hair. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">30. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff8040">Sweet dreams. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">31. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400000">Hot chocolate.</SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900"> </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">32. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #008040">Road trips with friends. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">33. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080c0">Swinging on swings. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">34. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #800040">Making eye contact with a cute stranger. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">35. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: olive">Making chocolate chip cookies. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">36. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080c0">Having your friends send you homemade cookies. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">37. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: maroon">Holding hands with someone you care about. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">38. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #004080">Running into an old friend and realizing that some things (good or bad) never change. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">39. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080c0">Watching the expression on someone's face as they open a much desired present from you. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">40. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: teal">Watching the sunrise. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">41. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400040">Getting out of bed every morning and being grateful for another beautiful day. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">42. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #004080">Knowing that somebody misses you. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">43. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff0080">Getting a hug from someone you care about deeply. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">44. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009933">Knowing you've done the right thing, no matter what other people think. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: black">Pass on These Natural Highs to at Least 7 People in the Next Half Hour and Something Fantastic Will Happen to You in the Next Few Hours. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: black">Be sure to send it back to the person who sent it to you! </SPAN></I></DIV></DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><U><SPAN style="FONT-SIZE: 36pt; COLOR: black">Lord, keep Your arm around my shoulder and Your hand over my mouth </SPAN></U></I></B><I><SPAN style="FONT-SIZE: 36pt; COLOR: black">. </SPAN></I></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV>
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></BLOCKQUOTE></DIV></DIV></BLOCKQUOTE></TD></TR></TBODY></TABLE>
<DIV>
<DIV>&nbsp;</DIV></DIV></BLOCKQUOTE></DIV>
<DIV style="MARGIN-BOTTOM: 12pt">
<DIV>&nbsp;</DIV></DIV>
<DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center>&nbsp;</DIV></DIV></DIV></DIV>
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></DIV></TD></TR></TBODY></TABLE>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></BLOCKQUOTE></DIV></DIV>
<DIV>
<DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></BLOCKQUOTE></DIV></DIV></DIV></DIV></BLOCKQUOTE></DIV></BLOCKQUOTE></TD></TR></TBODY></TABLE>
<DIV>&nbsp;</DIV></BLOCKQUOTE>
<DIV><SPAN style="FONT-SIZE: 10pt"><BR><BR>____________________________________________________________ <BR><A href="http://thirdpartyoffers.teszero.tes/TGL2242/fc/Ioyw6i4s3vE7AtPVOoK3ONnM3QVDTHWxvMijDjWs9sLP0Me4bPnKz1/" target=_blank rel=nofollow>Click for free info on college degrees.</A></SPAN></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt; COLOR: black">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: black">It's time to go back to school! Get the latest trends and gadgets that make the grade on <A title=http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007 href="http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007" target=_blank rel=nofollow>AOL Shopping</A>.</SPAN> </DIV></DIV></DIV></BLOCKQUOTE></TD></TR></TBODY></TABLE>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt; COLOR: black">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: black">It's time to go back to school! Get the latest trends and gadgets that make the grade on <A title=http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007 href="http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007" target=_blank rel=nofollow>AOL Shopping</A>.</SPAN><SPAN style="FONT-SIZE: 10pt"> </SPAN></DIV></DIV></BLOCKQUOTE>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">See what people are saying about Windows Live. Check out featured posts. <A href="http://www.windowslive.tes/connect?ocid=TXT_TAGLM_WL_connect2_082008" target=_blank rel=nofollow>Check It Out!</A> </SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">Talk to your Yahoo! Friends via Windows Live Messenger. <A href="http://www.windowslive.tes/explore/messenger?ocid=TXT_TAGLM_WL_messenger_yahoo_082008" target=_blank rel=nofollow>Find Out How</A></SPAN></DIV></DIV></DIV></DIV><BR></DIV></DIV></DIV>
<DIV id=AOLMsgPart_15_509f09b8-680e-42dc-b2a0-66b9d4955120 style="FONT-SIZE: 12px; MARGIN: 0px; COLOR: #000; FONT-FAMILY: Tahoma, Verdana, Arial, Sans-Serif; BACKGROUND-COLOR: #fff"><PRE style="FONT-SIZE: 9pt"><TT>
</TT></PRE></DIV>
<DIV id=AOLMsgPart_16_509f09b8-680e-42dc-b2a0-66b9d4955120 style="MARGIN: 10px">
<DIV style="BORDER-RIGHT: #7da8d4 1px solid; BORDER-TOP: #7da8d4 1px solid; BACKGROUND: #f9f9f9; FONT: 11px arial; BORDER-LEFT: #7da8d4 1px solid; BORDER-BOTTOM: #7da8d4 1px solid">
<DIV style="PADDING-RIGHT: 3px; PADDING-LEFT: 3px; BACKGROUND: #b5ddfa; PADDING-BOTTOM: 3px; FONT: 11px arial; PADDING-TOP: 3px">Attached Message</DIV>
<TABLE>
<TBODY>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px" noWrap>From:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">CatchaLTR@example.com</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">To:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Pooh121549@example.com; pamras@example.com; beaglelover320@example.com; stacyyoung1971@example.com; jenabear520@example.com; ddukovac@example.com; vsoanes@example.com</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Subject:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Fwd: FW: NATURAL HIGHS</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Date:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Wed, 20 Aug 2008 13:26:48 -0400</TD></TR></TBODY></TABLE></DIV>
<DIV id=AOLMsgPart_20_509f09b8-680e-42dc-b2a0-66b9d4955120><FONT id=role_document face=Arial color=#000000 size=2>
<DIV>&nbsp;</DIV></FONT><BR><BR><BR>
<DIV><FONT style="FONT: 10pt ARIAL,; COLOR: black">
<HR style="MARGIN-TOP: 10px">
It's only a deal if it's where <I>you</I> want to go. Find your travel deal <A title=http://information.travel.aol.tes/deals?ncid=aoltrv00050000000047 href="http://information.travel.aol.tes/deals?ncid=aoltrv00050000000047" target=_blank rel=nofollow><B>here</B></A>.</FONT></DIV></DIV>
<DIV id=AOLMsgPart_21_509f09b8-680e-42dc-b2a0-66b9d4955120 style="MARGIN: 10px">
<DIV style="BORDER-RIGHT: #7da8d4 1px solid; BORDER-TOP: #7da8d4 1px solid; BACKGROUND: #f9f9f9; FONT: 11px arial; BORDER-LEFT: #7da8d4 1px solid; BORDER-BOTTOM: #7da8d4 1px solid">
<DIV style="PADDING-RIGHT: 3px; PADDING-LEFT: 3px; BACKGROUND: #b5ddfa; PADDING-BOTTOM: 3px; FONT: 11px arial; PADDING-TOP: 3px">Attached Message</DIV>
<TABLE>
<TBODY>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px" noWrap>From:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Stacy Young &lt;stacyyoung1971@example.com&gt;</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">To:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Marlana &lt;catchaLTR@example.com&gt;; Mom &lt;cwbbqcateringco@example.com&gt;; Pat &lt;preycroft@example.com&gt;; Veronica &lt;youngmyakka@example.com&gt;; Sharon &amp; Dan &lt;dpriff3@example.com&gt;; Dad &amp; Linda &lt;lincliff@example.com&gt;; Kelley Hightower &lt;KHightower@example.com&gt;; Nicole &lt;ybbyancey@example.com&gt;; Tammy &lt;tammy@example.com&gt;; Charlie &lt;most_definitly@example.com&gt;; Cousin Angie &lt;angela.alderson1@example.com&gt;; Barbara &lt;bjbandish@example.com&gt;; Debra &lt;debra.gallipo@example.com&gt;; Cyndy &lt;cyndysota34287@example.com&gt;; Tena &lt;fleiniebop1@example.com&gt;; Laurie &lt;lloseemail@example.com&gt;; Holly &lt;happyholly@example.com&gt;</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Subject:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Fwd: FW: NATURAL HIGHS</TD></TR>
<TR vAlign=top>
<TD style="PADDING-RIGHT: 10px; PADDING-LEFT: 9px; BACKGROUND: #f9f9f9; PADDING-BOTTOM: 1px; FONT: 11px arial; COLOR: #000000; PADDING-TOP: 1px">Date:</TD>
<TD style="BACKGROUND: #f9f9f9; FONT: 11px arial; COLOR: #000000">Wed, 20 Aug 2008 10:37:40 -0400</TD></TR></TBODY></TABLE></DIV>
<DIV id=AOLMsgPart_26_509f09b8-680e-42dc-b2a0-66b9d4955120>
<DIV dir=ltr><BR><BR>
<DIV class=gmail_quote>---------- Forwarded message ----------<BR>From: <B class=gmail_sendername>Stacy Young</B> <SPAN dir=ltr>&lt;<A href="mailto:SYoung@example.com" target=_blank rel=nofollow>SYoung@example.com</A>&gt;</SPAN><BR>Date: Wed, Aug 20, 2008 at 10:35 AM<BR>Subject: FW: NATURAL HIGHS<BR>To: <A href="mailto:stacyyoung1971@example.com" target=_blank rel=nofollow>stacyyoung1971@example.com</A><BR>Cc: Lisa Robertson &lt;<A href="mailto:LRobertson@example.com" target=_blank rel=nofollow>LRobertson@example.com</A>&gt;<BR><BR><BR>
<DIV lang=EN-US>
<DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV>
<DIV><SPAN style="FONT-SIZE: 13.5pt; COLOR: #1f497d">Stacy Young</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Underwriter</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">FWCJUA</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Tel:&nbsp; 941.378.7400 ext 5427</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Fax:&nbsp; 941.487.2532</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d"><A href="mailto:syoung@example.com" target=_blank rel=nofollow>syoung@example.com</A></SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: black">*****************************************************************************************<BR>This message may contain information that is privileged, confidential and exempt from<BR>disclosure under applicable law. If you are not the intended recipient (or authorized to<BR>act on behalf of the intended recipient) of this message, you may not disclose, forward,<BR>distribute, copy, or use this message or its contents.&nbsp; If you have received this<BR>communication in error, please notify us immediately by return e-mail and delete the<BR>original message from your e-mail system.<BR>*****************************************************************************************</SPAN><SPAN style="COLOR: black"></SPAN></DIV></DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV>
<DIV style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: #b5c4df 1pt solid; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; BORDER-LEFT: medium none; PADDING-TOP: 3pt; BORDER-BOTTOM: medium none">
<DIV><B><SPAN style="FONT-SIZE: 10pt">From:</SPAN></B><SPAN style="FONT-SIZE: 10pt"> Lisa Robertson <BR><B>Sent:</B> Wednesday, August 20, 2008 7:54 AM<BR><B>To:</B> Janis Scott; Lisa M. Pisani; Stacy Young; Susan J. Schmidtke; Terri Woods<BR><B>Subject:</B> FW: NATURAL HIGHS</SPAN></DIV></DIV></DIV>
<DIV>&nbsp;</DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV>
<DIV><SPAN style="COLOR: #1f497d">&nbsp;</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Lisa Robertson</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Underwriting Supervisor</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">FWCJUA</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Phone: 941-378-7400</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d">Fax: 941-487-2531</SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: #1f497d"><A href="mailto:lrobertson@example.com" target=_blank rel=nofollow>lrobertson@example.com</A></SPAN><SPAN style="COLOR: #1f497d"></SPAN></DIV></DIV>
<DIV><SPAN style="COLOR: #1f497d">&nbsp;</SPAN><SPAN style="FONT-SIZE: 11pt; COLOR: #1f497d"></SPAN></DIV>
<DIV>
<DIV style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: #b5c4df 1pt solid; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; BORDER-LEFT: medium none; PADDING-TOP: 3pt; BORDER-BOTTOM: medium none">
<DIV><B><SPAN style="FONT-SIZE: 10pt">From:</SPAN></B><SPAN style="FONT-SIZE: 10pt"> michael rankin [mailto:<A href="mailto:michaelggrankin@example.com" target=_blank rel=nofollow>michaelggrankin@example.com</A>] <BR><B>Sent:</B> Monday, August 18, 2008 7:51 PM<BR><B>To:</B> Lisa Robertson<BR><B>Subject:</B> FW: NATURAL HIGHS</SPAN></DIV></DIV></DIV>
<DIV>&nbsp;</DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt"><BR><BR></SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt">From: <A href="mailto:ikhardy44@example.com" target=_blank rel=nofollow>ikhardy44@example.com</A><BR>To: <A href="mailto:taraberry@example.com" target=_blank rel=nofollow>taraberry@example.com</A>; <A href="mailto:flowerbug98@example.com" target=_blank rel=nofollow>flowerbug98@example.com</A>; <A href="mailto:dennis.smith86@example.com" target=_blank rel=nofollow>dennis.smith86@example.com</A>; <A href="mailto:karlbeulah@example.com" target=_blank rel=nofollow>karlbeulah@example.com</A>; <A href="mailto:lbaker45@example.com" target=_blank rel=nofollow>lbaker45@example.com</A>; <A href="mailto:michaelggrankin@example.com" target=_blank rel=nofollow>michaelggrankin@example.com</A>; <A href="mailto:nikki67888@example.com" target=_blank rel=nofollow>nikki67888@example.com</A>; <A href="mailto:rolin3991@example.com" target=_blank rel=nofollow>rolin3991@example.com</A>; <A href="mailto:suziewhi@example.com" target=_blank
 rel=nofollow>suziewhi@example.com</A><BR>Subject: FW: NATURAL HIGHS<BR>Date: Mon, 18 Aug 2008 19:35:40 -0400<BR><BR></SPAN></DIV>
<DIV>
<DIV><SPAN style="BORDER-RIGHT: windowtext 1pt solid; PADDING-RIGHT: 0in; BORDER-TOP: windowtext 1pt solid; PADDING-LEFT: 0in; FONT-SIZE: 10pt; PADDING-BOTTOM: 0in; BORDER-LEFT: windowtext 1pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: windowtext 1pt solid"></SPAN><SPAN style="FONT-SIZE: 10pt">irene..............</SPAN><SPAN style="FONT-SIZE: 10pt"></SPAN></DIV></DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV style="MARGIN-BOTTOM: 12pt"><SPAN style="FONT-SIZE: 10pt">From: <A href="mailto:catherinedicker@example.com" target=_blank rel=nofollow>catherinedicker@example.com</A><BR>To: <A href="mailto:CCREIN@example.com" target=_blank rel=nofollow>CCREIN@example.com</A>; <A href="mailto:MaryBeth@example.com" target=_blank rel=nofollow>MaryBeth@example.com</A>; <A href="mailto:amcgourty@example.com" target=_blank rel=nofollow>amcgourty@example.com</A>; <A href="mailto:SMSCMAC@example.com" target=_blank rel=nofollow>SMSCMAC@example.com</A>; <A href="mailto:ikhardy44@example.com" target=_blank rel=nofollow>ikhardy44@example.com</A>; <A href="mailto:Moeful@example.com" target=_blank rel=nofollow>Moeful@example.com</A>; <A href="mailto:HUNNA002@example.com" target=_blank rel=nofollow>HUNNA002@example.com</A>; <A href="mailto:bgb4477@example.com" target=_blank rel=nofollow>bgb4477@example.com</A><BR>Subject: Fwd: NATURAL HIGHS<BR>Date: Sun, 17 Aug 2008 18:31:03
 +0000</SPAN></DIV>
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV></DIV>
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV></DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">Date: Fri, 8 Aug 2008 13:37:50 +0000 </SPAN></DIV>
<TABLE cellSpacing=0 cellPadding=0 border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; PADDING-LEFT: 4pt; PADDING-BOTTOM: 0in; MARGIN: 5pt 0in 5pt 3.75pt; BORDER-LEFT: black 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<TABLE cellSpacing=0 cellPadding=0 border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">----- Original Message ----- </SPAN></DIV>
<DIV>
<DIV><B><SPAN style="FONT-SIZE: 10pt">Subject:</SPAN></B><SPAN style="FONT-SIZE: 10pt"> Fwd: NATURAL HIGHS</SPAN></DIV></DIV></DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV>
<DIV>
<DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>&nbsp;</DIV>
<DIV>
<TABLE cellSpacing=0 cellPadding=0 border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<DIV>
<DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: windowtext 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<TABLE style="BACKGROUND: white; MARGIN-LEFT: 10.75pt; WIDTH: 97.8%" cellSpacing=0 cellPadding=0 width="97%" border=0>
<TBODY>
<TR>
<TD style="PADDING-RIGHT: 0in; PADDING-LEFT: 0in; PADDING-BOTTOM: 0in; PADDING-TOP: 0in" vAlign=top>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: windowtext 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<BLOCKQUOTE style="MARGIN-TOP: 5pt; MARGIN-BOTTOM: 5pt">
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV><B><I><U><SPAN style="FONT-SIZE: 36pt; COLOR: black">N</SPAN></U></I></B><B><I><U><SPAN style="FONT-SIZE: 36pt; COLOR: #990000">atural Highs </SPAN></U></I></B></DIV></DIV></DIV></DIV></DIV></DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV style="MARGIN-BOTTOM: 5pt">
<DIV>
<DIV style="MARGIN-BOTTOM: 7.5pt; MARGIN-LEFT: 7.5pt; MARGIN-RIGHT: 7.5pt">
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #990000">Please make </SPAN></I></B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #990000">sure<B> you forward this back to me . . You'll see why at the end. Think about them one at a time before going on to the next one. It Does Make You Feel Good, especially the thought at the end of #44. </B></SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">1. Falling in love. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">2. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff8000">Laughing so hard your face hurts. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">3. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff0080">A hot shower. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">4. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0000a0">No lines at the supermarket</SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900"> . </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">5. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #808040">A special glance. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">6. </SPAN></I></B><B><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400040">Getting mail. </SPAN></I></B></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">7. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080ff">Taking a drive on a pretty road. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">8. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff80ff">Hearing your favorite song on the radio. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">9. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: maroon">Lying in bed listening to the rain outside. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">10. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080ff">Hot towels fresh out of the dryer. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">11. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #008040">Chocolate milkshake (vanilla or strawberry). </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">12. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8000ff">A bubble bath. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">13. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: red">Giggling. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">15. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080ff">The beach. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">16. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff0080">Finding a 20 dollar bill in your coat from last winter. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">17. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #808040">Laughing at yourself. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">18. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080c0">Looking into their eyes and knowing they Love you </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">19. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #804040">Midnight phone calls that last for hours. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">20. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400080">Running through sprinklers.</SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900"> </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">21. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff5353">Laughing for absolutely no reason at all. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">22. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #000040">Having someone tell you that you're beautiful. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">23. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400080">Laughing at an inside joke with FRIENDS </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">24. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff8000">Accidentally overhearing someone say something nice about you. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">25. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080ff">Waking up and realizing you still have a few hours left to sleep. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">26. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff80ff">Your first kiss (either the very first or with a new partner). </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">27. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080c0">Making new friends or spending time with old ones. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">28. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400000">Playing with a new puppy. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">29. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: blue">Having someone play with your hair. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">30. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff8040">Sweet dreams. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">31. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400000">Hot chocolate.</SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900"> </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">32. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #008040">Road trips with friends. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">33. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #0080c0">Swinging on swings. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">34. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #800040">Making eye contact with a cute stranger. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">35. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: olive">Making chocolate chip cookies. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">36. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080c0">Having your friends send you homemade cookies. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">37. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: maroon">Holding hands with someone you care about. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">38. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #004080">Running into an old friend and realizing that some things (good or bad) never change. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">39. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #8080c0">Watching the expression on someone's face as they open a much desired present from you. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">40. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: teal">Watching the sunrise. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">41. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #400040">Getting out of bed every morning and being grateful for another beautiful day. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">42. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #004080">Knowing that somebody misses you. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">43. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #ff0080">Getting a hug from someone you care about deeply. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009900">44. </SPAN></I><I><SPAN style="FONT-SIZE: 36pt; COLOR: #009933">Knowing you've done the right thing, no matter what other people think. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: black">Pass on These Natural Highs to at Least 7 People in the Next Half Hour and Something Fantastic Will Happen to You in the Next Few Hours. </SPAN></I></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><I><SPAN style="FONT-SIZE: 36pt; COLOR: black">Be sure to send it back to the person who sent it to you! </SPAN></I></DIV></DIV>
<DIV style="TEXT-ALIGN: center" align=center><B><I><U><SPAN style="FONT-SIZE: 36pt; COLOR: black">Lord, keep Your arm around my shoulder and Your hand over my mouth </SPAN></U></I></B><I><SPAN style="FONT-SIZE: 36pt; COLOR: black">. </SPAN></I></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV></DIV>
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></BLOCKQUOTE></DIV></DIV></BLOCKQUOTE></TD></TR></TBODY></TABLE>
<DIV>
<DIV>&nbsp;</DIV></DIV></BLOCKQUOTE></DIV>
<DIV style="MARGIN-BOTTOM: 12pt">
<DIV>&nbsp;</DIV></DIV>
<DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center>&nbsp;</DIV></DIV></DIV></DIV>
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></DIV></TD></TR></TBODY></TABLE>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></BLOCKQUOTE></DIV></DIV>
<DIV>
<DIV>
<DIV>
<BLOCKQUOTE style="BORDER-RIGHT: medium none; PADDING-RIGHT: 0in; BORDER-TOP: medium none; MARGIN-TOP: 5pt; PADDING-LEFT: 4pt; MARGIN-BOTTOM: 5pt; PADDING-BOTTOM: 0in; MARGIN-LEFT: 3.75pt; BORDER-LEFT: #1010ff 1.5pt solid; PADDING-TOP: 0in; BORDER-BOTTOM: medium none">
<DIV>
<DIV>
<DIV>&nbsp;</DIV></DIV></DIV></BLOCKQUOTE></DIV></DIV></DIV></DIV></BLOCKQUOTE></DIV></BLOCKQUOTE></TD></TR></TBODY></TABLE>
<DIV>&nbsp;</DIV></BLOCKQUOTE>
<DIV><SPAN style="FONT-SIZE: 10pt"><BR><BR>____________________________________________________________ <BR><A href="http://thirdpartyoffers.teszero.tes/TGL2242/fc/Ioyw6i4s3vE7AtPVOoK3ONnM3QVDTHWxvMijDjWs9sLP0Me4bPnKz1/" target=_blank rel=nofollow>Click for free info on college degrees.</A></SPAN></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt; COLOR: black">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: black">It's time to go back to school! Get the latest trends and gadgets that make the grade on <A title=http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007 href="http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007" target=_blank rel=nofollow>AOL Shopping</A>.</SPAN> </DIV></DIV></DIV></BLOCKQUOTE></TD></TR></TBODY></TABLE>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV></DIV>
<DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt; COLOR: black">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt; COLOR: black">It's time to go back to school! Get the latest trends and gadgets that make the grade on <A title=http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007 href="http://shopping.aol.tes/back-to-school?ncid=aolins00050000000007" target=_blank rel=nofollow>AOL Shopping</A>.</SPAN><SPAN style="FONT-SIZE: 10pt"> </SPAN></DIV></DIV></BLOCKQUOTE>
<DIV><SPAN style="FONT-SIZE: 10pt">&nbsp;</SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">See what people are saying about Windows Live. Check out featured posts. <A href="http://www.windowslive.tes/connect?ocid=TXT_TAGLM_WL_connect2_082008" target=_blank rel=nofollow>Check It Out!</A> </SPAN></DIV>
<DIV style="TEXT-ALIGN: center" align=center><SPAN style="FONT-SIZE: 10pt">
<HR align=center width="100%" SIZE=2>
</SPAN></DIV>
<DIV><SPAN style="FONT-SIZE: 10pt">Talk to your Yahoo! Friends via Windows Live Messenger. <A href="http://www.windowslive.tes/explore/messenger?ocid=TXT_TAGLM_WL_messenger_yahoo_082008" target=_blank rel=nofollow>Find Out How</A></SPAN></DIV></DIV></DIV></DIV><BR></DIV></DIV></DIV>
<DIV id=AOLMsgPart_29_509f09b8-680e-42dc-b2a0-66b9d4955120 style="FONT-SIZE: 12px; MARGIN: 0px; COLOR: #000; FONT-FAMILY: Tahoma, Verdana, Arial, Sans-Serif; BACKGROUND-COLOR: #fff"><PRE style="FONT-SIZE: 9pt"><TT>
</TT></PRE></DIV></DIV></DIV><BR>
<DIV id=AOLMsgPart_27_509f09b8-680e-42dc-b2a0-66b9d4955120 style="MARGIN: 10px"><A href="http://webmail.aol.tes/38491/aim/en-us/Mail/get-attachment.aspx?uid=1.20689356&amp;folder=Inbox&amp;partId=27" target=_blank rel=nofollow>[Image Removed] <BR></A></DIV>
<DIV class=aol_ad_footer id=u8CAD43962977AE3-E28-13F><FONT style="FONT: 10pt ARIAL,; COLOR: black">
<HR style="MARGIN-TOP: 10px">
<A title=http://mapquest.tes/toolbar?ncid=mpqmap00050000000010 href="http://mapquest.tes/toolbar?ncid=mpqmap00050000000010" target=_blank rel=nofollow>Get the MapQuest Toolbar</A>. Directions, Traffic, Gas Prices &amp; More!</FONT> </DIV></DIV></BLOCKQUOTE></td></tr></table><br>

      
--0-505355714-1219666281=:64492
Content-Type: image/jpeg; name="image001.jpg"
Content-Transfer-Encoding: base64
Content-Id: <1.1498461367@example.com>

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8l
JCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/wAALCAAMAAwBAREA/8QAHwAA
AQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQR
BRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RF
RkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ip
qrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oACAEB
AAA/APZqKKK//9k=

--0-505355714-1219666281=:64492--
--0-1701094651-1219666281=:64492--
--0-831998417-1219666281=:64492
Content-Type: application/octet-stream; name=Header
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=Header

UmV0dXJuLXBhdGg6IDw+DQpSZXR1cm4tUGF0aDogPHN0YWN5eW91bmcxOTcxQGdtYWlsLmNv
bT4NClJlY2VpdmVkOiBmcm9tIHJseS1kYjAzLm14LmFvbC5jb20gKHJseS1kYjAzLm1haWwu
YW9sLmNvbSBbMTcyLjE5LjEzMC43OF0pIGJ5IGFpci1kYjEwLm1haWwuYW9sLmNvbSAodjEy
MV9yMi4xMSkgd2l0aCBFU01UUCBpZCBNQUlMSU5EQjEwMy1hYjk0OGFjMmMzNTFlOTsgV2Vk
LCAyMCBBdWcgMjAwOCAxMDozODoxNiAtMDQwMA0KUmVjZWl2ZWQ6IGZyb20gd2Ytb3V0LTEz
MTQuZ29vZ2xlLmNvbSAod2Ytb3V0LTEzMTQuZ29vZ2xlLmNvbSBbMjA5Ljg1LjIwMC4xNjld
KSBieSBybHktZGIwMy5teC5hb2wuY29tICh2MTIxX3IyLjExKSB3aXRoIEVTTVRQIGlkIE1B
SUxSRUxBWUlOREIwMzctYWI5NDhhYzJjMzUxZTk7IFdlZCwgMjAgQXVnIDIwMDggMTA6Mzc6
NDEgLTA0MDANClJlY2VpdmVkOiBieSB3Zi1vdXQtMTMxNC5nb29nbGUuY29tIHdpdGggU01U
UCBpZCAyOHNvNDc0MjMzd2ZjLjE4DQogICAgICAgIGZvciA8Y2F0Y2hhTFRSQGFvbC5jb20+
OyBXZWQsIDIwIEF1ZyAyMDA4IDA3OjM3OjQxIC0wNzAwIChQRFQpDQpES0lNLVNpZ25hdHVy
ZTogdj0xOyBhPXJzYS1zaGEyNTY7IGM9cmVsYXhlZC9yZWxheGVkOw0KICAgICAgICBkPWdt
YWlsLmNvbTsgcz1nYW1tYTsNCiAgICAgICAgaD1kb21haW5rZXktc2lnbmF0dXJlOnJlY2Vp
dmVkOnJlY2VpdmVkOm1lc3NhZ2UtaWQ6ZGF0ZTpmcm9tOnRvDQogICAgICAgICA6c3ViamVj
dDppbi1yZXBseS10bzptaW1lLXZlcnNpb246Y29udGVudC10eXBlOnJlZmVyZW5jZXM7DQog
ICAgICAgIGJoPU9MdlE1VjNDcDF6bkJpSzhmTTh6TmoyL2k4d295Q09jajNWT2cyV0txc3M9
Ow0KICAgICAgICBiPUlJbWRxVzJQZGxvZ2NXbTBhTnZZNlRMblpMQ0NjZHB5cVBGUHNNalRW
WkFKb3RWRENveFBYZ1pYZW5RREpBanMrRw0KICAgICAgICAgaS92cUZraFUybGt1V0FEUEV1
U0FEazRVRUpQMFpySTRtQzc2VHY5ZDUzLzM3L2xxY01BOVc3eG1qcjJib0w2YzBnTloNCiAg
ICAgICAgIDJteDdVbjNERXFrS3p5S3NYSUkxZXcrc0dUMERlK0VESlc3dkU9DQpEb21haW5L
ZXktU2lnbmF0dXJlOiBhPXJzYS1zaGExOyBjPW5vZndzOw0KICAgICAgICBkPWdtYWlsLmNv
bTsgcz1nYW1tYTsNCiAgICAgICAgaD1tZXNzYWdlLWlkOmRhdGU6ZnJvbTp0bzpzdWJqZWN0
OmluLXJlcGx5LXRvOm1pbWUtdmVyc2lvbg0KICAgICAgICAgOmNvbnRlbnQtdHlwZTpyZWZl
cmVuY2VzOw0KICAgICAgICBiPWhoWkhTa1p3Q3JPT2ZiaUNvRUR0eFN0NERobEdMTXlyelNC
VGdROVVjQkViY2hjWFlsQnd0eUFmRzhzQW83S3hoYw0KICAgICAgICAgNzhYNzNxT1RmdDZK
SE9xc3Fnb2daYWtkS3BrQVIrVERKaFpjTFJLOWZmSk5tWlJ3S1BJTEYzd3BJWDk0M1BxenVq
bXINCiAgICAgICAgIGk0Y2hkTWw1VU45R3IvNndlNkRjc096QUdmcXBCWUlOVndUNTg9DQpS
ZWNlaXZlZDogYnkgMTAuMTQyLjE2NC4xMCB3aXRoIFNNVFAgaWQgbTEwbXI0NTM2N3dmZS42
MC4xMjE5MjQzMDYwNjgwOw0KICAgICAgICBXZWQsIDIwIEF1ZyAyMDA4IDA3OjM3OjQwIC0w
NzAwIChQRFQpDQpSZWNlaXZlZDogYnkgMTAuMTQzLjQ0LjYgd2l0aCBIVFRQOyBXZWQsIDIw
IEF1ZyAyMDA4IDA3OjM3OjQwIC0wNzAwIChQRFQpDQpNZXNzYWdlLUlEOiA8YmZhNWRjMzUw
ODA4MjAwNzM3ajJmYWJhMGE1eWVjMTI2MjdhYTk1YTM4NTlAbWFpbC5nbWFpbC5jb20+DQpE
YXRlOiBXZWQsIDIwIEF1ZyAyMDA4IDEwOjM3OjQwIC0wNDAwDQpGcm9tOiAiU3RhY3kgWW91
bmciIDxzdGFjeXlvdW5nMTk3MUBnbWFpbC5jb20+DQpUbzogIkNvdXNpbiBBbmdpZSIgPGFu
Z2VsYS5hbGRlcnNvbjFAdXMuYXJteS5taWw+LA0KICAgICAgICBCYXJiYXJhIDxiamJhbmRp
c2hAdmVyaXpvbi5uZXQ+LCBNb20gPGN3YmJxY2F0ZXJpbmdjb0Bhb2wuY29tPiwNCiAgICAg
ICAgQ3luZHkgPGN5bmR5c290YTM0Mjg3QHlhaG9vLmNvbT4sIE1hcmxhbmEgPGNhdGNoYUxU
UkBhb2wuY29tPiwNCiAgICAgICAgQ2hhcmxpZSA8bW9zdF9kZWZpbml0bHlAbWluZGxlc3Mu
Y29tPiwNCiAgICAgICAgRGVicmEgPGRlYnJhLmdhbGxpcG9AdmVyaXpvbi5uZXQ+LA0KICAg
ICAgICAiRGFkICYgTGluZGEiIDxsaW5jbGlmZkBob3RtYWlsLmNvbT4sDQogICAgICAgICJT
aGFyb24gJiBEYW4iIDxkcHJpZmYzQGVhcnRobGluay5uZXQ+LCBUZW5hIDxmbGVpbmllYm9w
MUB5YWhvby5jb20+LA0KICAgICAgICBIb2xseSA8aGFwcHlob2xseUB5b3Vub2xpa2UuY29t
PiwNCiAgICAgICAgIktlbGxleSBIaWdodG93ZXIiIDxLSGlnaHRvd2VyQGp1ZDEyLmZsY291
cnRzLm9yZz4sDQogICAgICAgIExhdXJpZSA8bGxvc2VlbWFpbEB5YWhvby5jb20+LCBOaWNv
bGUgPHliYnlhbmNleUBtYWlsbXQuY29tPiwNCiAgICAgICAgUGF0IDxwcmV5Y3JvZnRAY2hy
aXNjcmFmdC5jb20+LCBUYW1teSA8dGFtbXlAbWljdHJvbi5uZXQ+LA0KICAgICAgICBWZXJv
bmljYSA8eW91bmdteWFra2FAY3MuY29tPg0KU3ViamVjdDogRndkOiBGVzogTkFUVVJBTCBI
SUdIUw0KSW4tUmVwbHktVG86IDxBQkE0ODk2MUMyQTk5QzQ4QUQ4MTRGRDFCQzgwNDgwNzM3
NDFCQ0BhdGxhcy5md2NqdWEuY29tPg0KTUlNRS1WZXJzaW9uOiAxLjANCkNvbnRlbnQtVHlw
ZTogbXVsdGlwYXJ0L3JlbGF0ZWQ7IA0KCWJvdW5kYXJ5PSItLS0tPV9QYXJ0XzMxMTY4XzM3
MTk1NC4xMjE5MjQzMDYwNjU1Ig0KUmVmZXJlbmNlczogPEFCQTQ4OTYxQzJBOTlDNDhBRDgx
NEZEMUJDODA0ODA3Mzc0MUJDQGF0bGFzLmZ3Y2p1YS5jb20+DQpYLUFPTC1JUDogMjA5Ljg1
LjIwMC4xNjkNClgtQU9MLVNDT0xMLUFVVEhFTlRJQ0FUSU9OOiBsaXN0ZW5haXIgOyBTUEZf
aGVsbyA6IG4NClgtQU9MLVNDT0xMLUFVVEhFTlRJQ0FUSU9OOiBsaXN0ZW5haXIgOyBTUEZf
ODIyX2Zyb20gOiArDQpYLU1haWxlcjogVW5rbm93biAoTm8gVmVyc2lvbik=

--0-831998417-1219666281=:64492
Content-Type: image/jpeg; name="image001.jpg"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="image001.jpg"

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8l
JCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/wAALCAAMAAwBAREA/8QAHwAA
AQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQR
BRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RF
RkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ip
qrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oACAEB
AAA/APZqKKK//9k=

--0-831998417-1219666281=:64492
Content-Type: application/octet-stream; name=Header
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=Header

UmV0dXJuLXBhdGg6IDw+DQpSZXR1cm4tUGF0aDogPHN0YWN5eW91bmcxOTcxQGdtYWlsLmNv
bT4NClJlY2VpdmVkOiBmcm9tIHJseS1kYjAzLm14LmFvbC5jb20gKHJseS1kYjAzLm1haWwu
YW9sLmNvbSBbMTcyLjE5LjEzMC43OF0pIGJ5IGFpci1kYjEwLm1haWwuYW9sLmNvbSAodjEy
MV9yMi4xMSkgd2l0aCBFU01UUCBpZCBNQUlMSU5EQjEwMy1hYjk0OGFjMmMzNTFlOTsgV2Vk
LCAyMCBBdWcgMjAwOCAxMDozODoxNiAtMDQwMA0KUmVjZWl2ZWQ6IGZyb20gd2Ytb3V0LTEz
MTQuZ29vZ2xlLmNvbSAod2Ytb3V0LTEzMTQuZ29vZ2xlLmNvbSBbMjA5Ljg1LjIwMC4xNjld
KSBieSBybHktZGIwMy5teC5hb2wuY29tICh2MTIxX3IyLjExKSB3aXRoIEVTTVRQIGlkIE1B
SUxSRUxBWUlOREIwMzctYWI5NDhhYzJjMzUxZTk7IFdlZCwgMjAgQXVnIDIwMDggMTA6Mzc6
NDEgLTA0MDANClJlY2VpdmVkOiBieSB3Zi1vdXQtMTMxNC5nb29nbGUuY29tIHdpdGggU01U
UCBpZCAyOHNvNDc0MjMzd2ZjLjE4DQogICAgICAgIGZvciA8Y2F0Y2hhTFRSQGFvbC5jb20+
OyBXZWQsIDIwIEF1ZyAyMDA4IDA3OjM3OjQxIC0wNzAwIChQRFQpDQpES0lNLVNpZ25hdHVy
ZTogdj0xOyBhPXJzYS1zaGEyNTY7IGM9cmVsYXhlZC9yZWxheGVkOw0KICAgICAgICBkPWdt
YWlsLmNvbTsgcz1nYW1tYTsNCiAgICAgICAgaD1kb21haW5rZXktc2lnbmF0dXJlOnJlY2Vp
dmVkOnJlY2VpdmVkOm1lc3NhZ2UtaWQ6ZGF0ZTpmcm9tOnRvDQogICAgICAgICA6c3ViamVj
dDppbi1yZXBseS10bzptaW1lLXZlcnNpb246Y29udGVudC10eXBlOnJlZmVyZW5jZXM7DQog
ICAgICAgIGJoPU9MdlE1VjNDcDF6bkJpSzhmTTh6TmoyL2k4d295Q09jajNWT2cyV0txc3M9
Ow0KICAgICAgICBiPUlJbWRxVzJQZGxvZ2NXbTBhTnZZNlRMblpMQ0NjZHB5cVBGUHNNalRW
WkFKb3RWRENveFBYZ1pYZW5RREpBanMrRw0KICAgICAgICAgaS92cUZraFUybGt1V0FEUEV1
U0FEazRVRUpQMFpySTRtQzc2VHY5ZDUzLzM3L2xxY01BOVc3eG1qcjJib0w2YzBnTloNCiAg
ICAgICAgIDJteDdVbjNERXFrS3p5S3NYSUkxZXcrc0dUMERlK0VESlc3dkU9DQpEb21haW5L
ZXktU2lnbmF0dXJlOiBhPXJzYS1zaGExOyBjPW5vZndzOw0KICAgICAgICBkPWdtYWlsLmNv
bTsgcz1nYW1tYTsNCiAgICAgICAgaD1tZXNzYWdlLWlkOmRhdGU6ZnJvbTp0bzpzdWJqZWN0
OmluLXJlcGx5LXRvOm1pbWUtdmVyc2lvbg0KICAgICAgICAgOmNvbnRlbnQtdHlwZTpyZWZl
cmVuY2VzOw0KICAgICAgICBiPWhoWkhTa1p3Q3JPT2ZiaUNvRUR0eFN0NERobEdMTXlyelNC
VGdROVVjQkViY2hjWFlsQnd0eUFmRzhzQW83S3hoYw0KICAgICAgICAgNzhYNzNxT1RmdDZK
SE9xc3Fnb2daYWtkS3BrQVIrVERKaFpjTFJLOWZmSk5tWlJ3S1BJTEYzd3BJWDk0M1BxenVq
bXINCiAgICAgICAgIGk0Y2hkTWw1VU45R3IvNndlNkRjc096QUdmcXBCWUlOVndUNTg9DQpS
ZWNlaXZlZDogYnkgMTAuMTQyLjE2NC4xMCB3aXRoIFNNVFAgaWQgbTEwbXI0NTM2N3dmZS42
MC4xMjE5MjQzMDYwNjgwOw0KICAgICAgICBXZWQsIDIwIEF1ZyAyMDA4IDA3OjM3OjQwIC0w
NzAwIChQRFQpDQpSZWNlaXZlZDogYnkgMTAuMTQzLjQ0LjYgd2l0aCBIVFRQOyBXZWQsIDIw
IEF1ZyAyMDA4IDA3OjM3OjQwIC0wNzAwIChQRFQpDQpNZXNzYWdlLUlEOiA8YmZhNWRjMzUw
ODA4MjAwNzM3ajJmYWJhMGE1eWVjMTI2MjdhYTk1YTM4NTlAbWFpbC5nbWFpbC5jb20+DQpE
YXRlOiBXZWQsIDIwIEF1ZyAyMDA4IDEwOjM3OjQwIC0wNDAwDQpGcm9tOiAiU3RhY3kgWW91
bmciIDxzdGFjeXlvdW5nMTk3MUBnbWFpbC5jb20+DQpUbzogIkNvdXNpbiBBbmdpZSIgPGFu
Z2VsYS5hbGRlcnNvbjFAdXMuYXJteS5taWw+LA0KICAgICAgICBCYXJiYXJhIDxiamJhbmRp
c2hAdmVyaXpvbi5uZXQ+LCBNb20gPGN3YmJxY2F0ZXJpbmdjb0Bhb2wuY29tPiwNCiAgICAg
ICAgQ3luZHkgPGN5bmR5c290YTM0Mjg3QHlhaG9vLmNvbT4sIE1hcmxhbmEgPGNhdGNoYUxU
UkBhb2wuY29tPiwNCiAgICAgICAgQ2hhcmxpZSA8bW9zdF9kZWZpbml0bHlAbWluZGxlc3Mu
Y29tPiwNCiAgICAgICAgRGVicmEgPGRlYnJhLmdhbGxpcG9AdmVyaXpvbi5uZXQ+LA0KICAg
ICAgICAiRGFkICYgTGluZGEiIDxsaW5jbGlmZkBob3RtYWlsLmNvbT4sDQogICAgICAgICJT
aGFyb24gJiBEYW4iIDxkcHJpZmYzQGVhcnRobGluay5uZXQ+LCBUZW5hIDxmbGVpbmllYm9w
MUB5YWhvby5jb20+LA0KICAgICAgICBIb2xseSA8aGFwcHlob2xseUB5b3Vub2xpa2UuY29t
PiwNCiAgICAgICAgIktlbGxleSBIaWdodG93ZXIiIDxLSGlnaHRvd2VyQGp1ZDEyLmZsY291
cnRzLm9yZz4sDQogICAgICAgIExhdXJpZSA8bGxvc2VlbWFpbEB5YWhvby5jb20+LCBOaWNv
bGUgPHliYnlhbmNleUBtYWlsbXQuY29tPiwNCiAgICAgICAgUGF0IDxwcmV5Y3JvZnRAY2hy
aXNjcmFmdC5jb20+LCBUYW1teSA8dGFtbXlAbWljdHJvbi5uZXQ+LA0KICAgICAgICBWZXJv
bmljYSA8eW91bmdteWFra2FAY3MuY29tPg0KU3ViamVjdDogRndkOiBGVzogTkFUVVJBTCBI
SUdIUw0KSW4tUmVwbHktVG86IDxBQkE0ODk2MUMyQTk5QzQ4QUQ4MTRGRDFCQzgwNDgwNzM3
NDFCQ0BhdGxhcy5md2NqdWEuY29tPg0KTUlNRS1WZXJzaW9uOiAxLjANCkNvbnRlbnQtVHlw
ZTogbXVsdGlwYXJ0L3JlbGF0ZWQ7IA0KCWJvdW5kYXJ5PSItLS0tPV9QYXJ0XzMxMTY4XzM3
MTk1NC4xMjE5MjQzMDYwNjU1Ig0KUmVmZXJlbmNlczogPEFCQTQ4OTYxQzJBOTlDNDhBRDgx
NEZEMUJDODA0ODA3Mzc0MUJDQGF0bGFzLmZ3Y2p1YS5jb20+DQpYLUFPTC1JUDogMjA5Ljg1
LjIwMC4xNjkNClgtQU9MLVNDT0xMLUFVVEhFTlRJQ0FUSU9OOiBsaXN0ZW5haXIgOyBTUEZf
aGVsbyA6IG4NClgtQU9MLVNDT0xMLUFVVEhFTlRJQ0FUSU9OOiBsaXN0ZW5haXIgOyBTUEZf
ODIyX2Zyb20gOiArDQpYLU1haWxlcjogVW5rbm93biAoTm8gVmVyc2lvbik=

--0-831998417-1219666281=:64492
Content-Type: application/octet-stream; name=Header
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=Header

UmV0dXJuLXBhdGg6IDw+DQpYLUFwcGFyZW50bHktVG86IHBhbXJhc0BhdHQubmV0IHZpYSAy
MDkuMTkxLjg2LjE4ODsgV2VkLCAyMCBBdWcgMjAwOCAxMDoyNzowMCAtMDcwMA0KWC1Pcmln
aW5hdGluZy1JUDogWzEyLjEwMi4yNTIuODFdDQpBdXRoZW50aWNhdGlvbi1SZXN1bHRzOiBt
dGExMzYuc2JjLm1haWwucmUzLnlhaG9vLmNvbSAgZnJvbT1hb2wuY29tOyBkb21haW5rZXlz
PW5ldXRyYWwgKG5vIHNpZykNClJlY2VpdmVkOiBmcm9tIDEyLjEwMi4yNTIuODEgIChFSExP
IGFsbndteGMwMS5hdHQubmV0KSAoMTIuMTAyLjI1Mi44MSkNCiAgYnkgbXRhMTM2LnNiYy5t
YWlsLnJlMy55YWhvby5jb20gd2l0aCBTTVRQOyBXZWQsIDIwIEF1ZyAyMDA4IDEwOjI2OjU4
IC0wNzAwDQpSZWNlaXZlZDogZnJvbSBpbW8tZDA1Lm14LmFvbC5jb20gKFsyMDUuMTg4LjE1
Ny4zN10pDQogICAgICAgICAgYnkgYXR0Lm5ldCAoYWxud214YzAxKSB3aXRoIEVTTVRQDQog
ICAgICAgICAgaWQgPDIwMDgwODIwMTcyNjU1YTAxMDBoc3I0MmU+OyBXZWQsIDIwIEF1ZyAy
MDA4IDE3OjI2OjU1ICswMDAwDQpYLU9yaWdpbmF0aW5nLUlQOiBbMjA1LjE4OC4xNTcuMzdd
DQpSZWNlaXZlZDogZnJvbSBDYXRjaGFMVFJAYW9sLmNvbQ0KCWJ5IGltby1kMDUubXguYW9s
LmNvbSAobWFpbF9vdXRfdjM4X3IxMC44LikgaWQgMi5jNzkuM2RiMmJhYjkgKDMwNzQwKTsN
CglXZWQsIDIwIEF1ZyAyMDA4IDEzOjI2OjUxIC0wNDAwIChFRFQpDQpGcm9tOiBDYXRjaGFM
VFJAYW9sLmNvbQ0KRGF0ZTogV2VkLCAyMCBBdWcgMjAwOCAxMzoyNjo0OCBFRFQNClN1Ympl
Y3Q6IEZ3ZDogRlc6IE5BVFVSQUwgSElHSFMNClRvOiBiZWFnbGVsb3ZlcjMyMEBjb21jYXN0
Lm5ldCwgUG9vaDEyMTU0OUBhb2wuY29tLCBwYW1yYXNAYXR0Lm5ldCwNCiAgICAgICAgZGR1
a292YWNAeWFob28uY29tLCB2c29hbmVzQHlhaG9vLmNvbSwgamVuYWJlYXI1MjBAaG90bWFp
bC5jb20sDQogICAgICAgIHN0YWN5eW91bmcxOTcxQGdtYWlsLmNvbQ0KTUlNRS1WZXJzaW9u
OiAxLjANCkNvbnRlbnQtVHlwZTogbXVsdGlwYXJ0L21peGVkOyBib3VuZGFyeT0icGFydDFf
Yzc5LjNkYjJiYWI5LjM1ZGRhZGQ4X2JvdW5kYXJ5Ig0KWC1NYWlsZXI6IEFPTCA5LjAgVlIg
c3ViIDUwMDYNClgtU3BhbS1GbGFnOiBOTw0KQ29udGVudC1MZW5ndGg6IDg3MDg=

--0-831998417-1219666281=:64492--
