Return-Path: admin@zcs.srao.com
Received: from zcs.srao.com (LHLO zcs.srao.com) (10.117.83.62) by
 zcs.srao.com with LMTP; Fri, 11 Mar 2011 16:56:55 +0530 (IST)
Received: from localhost (localhost.localdomain [127.0.0.1])
	by zcs.srao.com (Postfix) with ESMTP id 07035E09BC
	for <u3@zcs.srao.com>; Fri, 11 Mar 2011 16:56:55 +0530 (IST)
X-Virus-Scanned: amavisd-new at zcs.srao.com
X-Spam-Flag: YES
X-Spam-Score: 7.19
X-Spam-Level: *******
X-Spam-Status: Yes, score=7.19 tagged_above=-10 required=6.6
	tests=[BAYES_50=0.8, DOS_OE_TO_MX=2.523, FSL_HELO_NON_FQDN_1=0.001,
	RDNS_NONE=0.793, SUBJECT_NEEDS_ENCODING=0.049, SUBJ_ALL_CAPS=1.506,
	SUBJ_ILLEGAL_CHARS=1.518] autolearn=no
Received: from zcs.srao.com ([127.0.0.1])
	by localhost (zcs.srao.com [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id b-oJbhkAdAhL for <u3@zcs.srao.com>;
	Fri, 11 Mar 2011 16:56:54 +0530 (IST)
Received: from pnqprasanth1 (unknown [10.117.81.35])
	by zcs.srao.com (Postfix) with SMTP id 8DD37E09BA
	for <u3@zcs.srao.com>; Fri, 11 Mar 2011 16:56:54 +0530 (IST)
Message-ID: <14EC76358B57423D971F39D2089C84C3@pnqprasanth1>
From: "admin" <admin@zcs.srao.com>
To: <u3@zcs.srao.com>
Subject: テスト  テスト
Date: Fri, 11 Mar 2011 17:15:10 +0530
MIME-Version: 1.0
Content-Type: text/plain;
	format=flowed;
	charset="iso-2022-jp";
	reply-type=response
Content-Transfer-Encoding: 7bit
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2900.5843
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2900.5579

テスト  テスト

